### ISSUE TITLE
Uncaught TypeError: $et_pb_ab_goal.visible is not a function

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#1000]
### Problem:

![2017-02-22_04-02-15-pm](https://cloud.githubusercontent.com/assets/4675662/23234663/636eae3a-f918-11e6-85d7-d969153a9b16.png)

### Steps To Reproduce:
1.  Edit an existing page using the VB.
2. Open the BB and set up a split test.
3. Switch to VB and check console.

## Attached PR

- https://github.com/elegantthemes/submodule-builder/pull/1755

**Comment by fikrirasyid** [comment]
Note: The issue is actually can be more consistently replicated if the  goal of the split test is number or circle counter because their VB components call `window.et_reinit_waypoint_modules();` on its `componentDidMount()`. For example:

```
<section>
	<row>
		<column>
			<slider> --- set as subject
		</column>
	</row>
	<row>
		<column>
			<numberCounter> - set as goal
		</column>
	</row>
</section>
```

Thus the complete steps are:

1. Open new page in BB
2. create layout above, publish
3. right click, open VB (dont focus on it), but give it few seconds to load
4. Enable split test
5. focus on VB, let sync, scroll down

Here's how the issue looks like:

![1000-divi-beta-issue](https://cloud.githubusercontent.com/assets/916442/23241644/c8f5658a-f9a6-11e6-9ca6-6e080f0253f0.gif)
