### ISSUE TITLE
Never-Ending BB Ajax Load. Impossible To Edit Page

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1002]
You can see the error by editing the following page in the BB:

http://elegantthemessiteground.com/wp-admin/post.php?post=80&action=edit

It's the homepage of our SiteGround hosting environment:

http://elegantthemessiteground.com/

### Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1758

**Comment by Jronk** [comment]
Im unable to replicate this. I visit http://elegantthemessiteground.com/wp-admin/post.php?post=80&action=edit and its loading just fine. I did some edits, and refreshes, etc, and syncs, but this is not occurring for me.

**Comment by Jronk** [comment]
I was able to replicate another time, and here is what is happening:
![screen shot 2017-02-22 at 5 12 03 pm](https://cloud.githubusercontent.com/assets/1163441/23240388/1c0efaae-f922-11e6-86d1-13d55f448bd8.png)

Somehow, both "editing" cookies are set at the same time. (they have a 5 minute shelf life currently, fwiw)

**Comment by timayhelen** [comment]
@Jronk Looks like you are right. This happened to me again and I was able to identify the double cookie et-editing-post cookie and the et-syncing-post cookie that wouldn't go away.

**Comment by Jronk** [comment]
yeah, that et-syncing-post cookie is the real root of the problem, but the two editing cookies is a symptom that is related the the syncing being there. This is most likely achievable if you close a tab/editor while its syncing. It will not get the chance to clear itself. So, the syncing cookie will linger for 5 mins. 

The fix on https://github.com/elegantthemes/submodule-builder/pull/1758 shortens the syncing cookie to 30 seconds rather than 5 mins, and makes sure it only can stall for 5 seconds max, not unlimited.
