### ISSUE TITLE
Builder Sync :: Don't Sync Properly

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1038]
### Problem:

Some options vanish when you don't close up module settings and switch between VB/BB.

To reproduce:
1. Under VB add Bar Counter module.
2. Go to BB, open Bar Counter settigns > First Tab Settigns > Define Title > Close only the tab settings (not bar counter settigns)
3. Switch to VB, open Bar Counter settigns.
4. Switch to BB Save/Close Bar Counter settings.
5. Switch to VB. You can see there is no defined title anymore.

Screen cast:
http://youtu.be/vO-7yw53qU8?hd=1

**Comment by fikrirasyid** [comment]
This is actually happens because how BB and VB work:

1. On VB, every change mutates the layout object and immediately queued for immediate heartbeat
2. On BB, the shortcode layout is re-generated (and later queued for heartbeat + saved for history) when modal setting is closed by clicking the `Save & Exit` button. 

The most possible way to fix this (that can think of right now) is by regenerating the shortcode every time settings modal fields' change events are triggered. However this process would be significantly heavy.

@Jronk @SlavaET @lots0logs  what do you guys think?

**Comment by lots0logs** [comment]
@fikrirasyid Could we simply trigger the BB's modal to Save/Close automatically when it loses focus (instead of the current behavior which simply closes it when it regains focus)?

**Comment by fikrirasyid** [comment]
@lots0logs can you elaborate more on that? I don't quite get it yet 🤔

**Comment by lots0logs** [comment]
@fikrirasyid Sure. Currently in the BB, how it works is that no changes made in the module settings are actually processed until the user Saves/Closes the settings modal. If the browser tab loses focus while the Module Settings modal is displayed, could we automatically process the changes to the settings as if the user would have Saved/Closed the modal before switching to another browser tab?

**Comment by fikrirasyid** [comment]
@lots0logs I see, it might work but I kinda worry about the lag because it takes quite time to rebuild the shortcode layout especially if the layout is complicated 🤔

**Comment by lots0logs** [comment]
@fikrirasyid 
> but I kinda worry about the lag

Sounds like a quick experiment is warranted :thinking:

**Comment by fikrirasyid** [comment]
@lots0logs I've been exploring your suggestion for and try implementing it but it appears that my concern is correct. I don't think it's possible to implement what you mentioned at https://github.com/elegantthemes/Divi-Beta/issues/1038#issuecomment-283204541 due to the lag of generating shortcode layout. In details:

1. What you suggested can be done by adding mouseleave events for `ET_PageBuilder.ModalView`
2. Whenever cursor leaves the tab, `this.performSaving()` is triggered which will fetch all the modal settings field data, then update the shortcode layout using these data.
3. The updated shortcode data then wait for the next heartbeat to be synced as autosave
4. When user switch back and forth between BB and VB, this approach will not work, because focusing out from window triggers the heartbeat to work in immediately; The sequence mentioned on step 1 until 3 needs more time than the time available between mouseleaving settings modal's tab and focusing out the window.

Consequently, when switching from BB (with opened settings modal and modified field) to VB, VB never gets the currently edited data from BB.

***

I'm currently working on alternative to this issue and it appears that the only way to make it work is by running `this.performSaving()` everytime fields are changed (the callback is throttled to avoid way too many process tho). I still need to figure out how to capture change events of tinyMCE and colorpicker (basically the non-standard fields).

**Comment by lots0logs** [comment]
@fikrirasyid We could use yet another cookie to inform the FB that it should throw its spinner and wait for the BB to finish up. This would only apply when the BB settings modal is opened at the time the user switches tabs. We'd also need to implement a flag so that the forced autosave doesn't occur when the settings modal is opened. Instead, the settings modal will initiate the autosave after it finishes processing changes.  What do you think?

**Comment by fikrirasyid** [comment]
@lots0logs about this:

> throw its spinner and wait for the BB to finish up

Is this still related to sync when cursor leaves the tab? If we're using this route, i think the spinner will appear quite long it becomes uncomfortable to way because it starts to sync late (sync late, spinner appear longer). I personally think it'd be much more seamless if we sync early and sync often, which is on input change / blur. My main concern with this route is this whether it is too heavy for browser to generate the shortcode every couple of second (when user types lots of stuff on inputs) or not.

**Comment by lots0logs** [comment]
> My main concern with this route is this whether it is too heavy for browser to generate the shortcode every couple of second (when user types lots of stuff on inputs) or not.

That is my main concern as well.

I think switching tabs while editing module settings in the BB without actually saving those settings yourself  first is not going to be a common workflow. Most people will save and close the modal themselves anyway.

Is the BB's shortcode generation process 100% client-side? I cant remember if it calls the server for anything, but if it does then I think doing it after every single change is not a good idea :thinking:

**Comment by timayhelen** [comment]
@lots0logs @fikrirasyid I don't think we need to worry about this. It's a "low priority" "improvement" so it's already at the bottom of our list, so we shouldn't bother fixing it unless there are no other bugs to fix, and if it's an easy fix.

**Comment by fikrirasyid** [comment]
@timayhelen noted. Let's revisit this when all higher priority issues has been fixed.

@lots0logs about this:

> Is the BB's shortcode generation process 100% client-side?

Yes it is. We directly generate the shortcode and insert it to the hidden main wp editor.
