### ISSUE TITLE
VB :: History Buttons Breaks Down VB

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1046]
### Problem:

So, when I add some changes, for example to blog module, then close the module and open Sections Module settings and click the Next/Prev changes button it breaks everything.

Screen cast:
http://youtu.be/0mJDrXi4kQA?hd=1

### Attached PR
* https://github.com/elegantthemes/submodule-builder/issues/1778

**Comment by SlavaET** [comment]
I referenced this issue by mistake in first place. I haven't had a chance to work on it yet.

**Comment by kary4** [comment]
Probably the following problem is related to this one: Everything disappears when I use History button under BB. 
Screen cast:
http://youtu.be/hg-WOP8MVyY?hd=1

**Comment by timayhelen** [comment]
@lots0logs This breaks pretty much all settings in the VB. They do not work until the settings modal is re-rendered. This should be heavily tested since the repercussions are apparently pretty broad. 

![lag](https://cloud.githubusercontent.com/assets/3333028/23375468/5c55ff04-fcdd-11e6-9d9a-c341fdf1d8d6.gif)

**Comment by lots0logs** [comment]
@timayhelen Turns out that I didn't commit the last change I made when I was testing the fix the other night :doh:
