### ISSUE TITLE
VB :: Comments Module :: No Reply Button

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#1064]
### Problem:

The option Show Reply Button simply does not work. No reply button appears.

Screen cast:
http://youtu.be/v5wSm0LJWjA?hd=1

**Comment by lceberg** [comment]
I believe this is actually caused by WordPress' weird logic of allowing comments. It seems the comments on the site were previously disabled which caused the comments for the post in question to be closed.

I checked the post with different theme and the reply button is still missing for that post ( http://elegantthemesbluehost.com/2010/09/15/hip-young-woman/ ) -- it says that comments are closed.

The reply button properly appears on new posts -- http://elegantthemesbluehost.com/2017/03/03/lorem-ipsum-dolor-sit-amet/

@timayhelen  @lots0logs do you think we need to update anything here ?

**Comment by lots0logs** [comment]
@lceberg We have another PR going through review that will automatically enable comments for post when a comments module is detected in the content. I think that will take care of this edge case.
