### ISSUE TITLE
It's Possible To Copy & Paste Split Testing Goals & Subjects Using Keyboard Shortcuts

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1078]
We can't allow split testing subjects and goals to be duplicated. It's currently possible using keyboard shortcodes in the VB & BB.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1811

**Comment by lots0logs** [comment]
@lceberg I noticed two things that need attention:

* In the BB, the "Paste" option is always shown in the right-click menu. The option should only be shown when its actually possible to perform the action.
* In the VB, the "Copy" option does not appear in the right-click menu when clicking on test subjects. Its also not possible to copy test subjects using the keyboard shortcuts.

**Comment by lceberg** [comment]
@lots0logs I added a fix that fixes the following issues with right click menu in BB:
- "Paste" / "Paste After" item appeared when an AB subject is copied and the page is refreshed without saving the started split testing (since the item is still in the clipboard)
- "Paste" / "Paste After" item appeared when trying to paste an AB subject in a different parent (column)

Can you please clarify how should AB subjects work in VB ? In BB we see all the subjects, for example:
![bb-subjects](https://cloud.githubusercontent.com/assets/1928328/23860132/b12b61ea-080e-11e7-9a9c-efbb69857f25.png)

In VB however there is only a single button visible (I'm not sure if AB options are present in VB at all), that is why I prevented them from being copied/pasted.

What should copying/pasting do for subjects in VB ?

**Comment by lceberg** [comment]
Just an update on this -- copy/pasting subjects is now possible in VB via right click and keyboard shortcuts.
I'm looking into making pasted subjects appear properly in order to avoid the following behavior:

![ab-subject-copy-paste](https://cloud.githubusercontent.com/assets/1928328/23917002/aba1aac0-08f6-11e7-98b9-5eadea12481c.gif)

**Comment by lceberg** [comment]
Split testing subject modules can now be properly copied/pasted in VB (the behavior displayed in the last comment is now fixed).

Props to Slava for helping with this last part. 🎉

**Comment by lots0logs** [comment]
@lceberg Its now possible to Cut them using <kbd>Ctrl</kbd>+<kbd>X</kbd> :grimacing:

**Comment by lceberg** [comment]
@lots0logs I pushed a fix for this and also updated the paste logic to prevent console errors when trying to paste after "prevented" cut.
