### ISSUE TITLE
Parallax Mode Reset / Not Working Correctly

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1084]
This is likely due to shortcode trimming. 

## Parallax Mode Reset

1. Create a new page in the BB.
2. Load the Homepage Basic layout.
3. Apply a background image to the section with the blurbs. 
4. Enable parallax mode and set the background to "True Parallax"
5. Publish the page. 
6. Click "Use Visual Builder"
7. Save the Page. 
8. Open the page in the BB again and check the section settings. The parallax mode will have changed to CSS. However, you will notice on the front end is still works as if parallax was enabled. 

## Parallax Mode Malfunction

1. Create a new page in the BB.
2. Load the Homepage Basic layout.
3. Apply a background image to the section with the blurbs. 
4. Enable parallax mode and set the background to "CSS"
5. Publish the page.
6. Check the page on the front end. CSS parallax mode is enabled/ 
7. Enable the Visual Builder. 
8. In the Visual Builder, parallax mode has been rendered as "True Parallax."
9. Save the page in the Visual Builder.
10. Check the front end to see that the parallax mode was switched to True Parallax. 
11. Open the page in the BB and check the section settings. Parallax mode says "CSS" in the BB even though it has been changed to "True Parallax" mode via the Visual Builder shortcode trimming bug.

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1821

**Comment by SlavaET** [comment]
Fixed. It happens because we used different default values in BB and VB/Frontend:
BB - `CSS`;
VB/Frontend = `True Parallax`.
So saving 'True Parallax' in VB defaults the value to `CSS` in BB and vice versa.
In my PR I set the `True Parallax` as default value for all the places and it works correctly now. Setting default value to `CSS` in all the places may break some websites becuase when rendering page on frontend we assume that default is `True Parallax` since it was the only effect at the beginning and we continue to use it as default for backward compatibility.
