### ISSUE TITLE
Divi Builder Doesn't Load On Firefox 52

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1088]
We have had a few reports of this. The Divi Backend Builder content area appears blank in the latest version of FireFox (52):

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=665093
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=664329
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=663594

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1824

**Comment by SlavaET** [comment]
It actually loads and it works you just need to hover over the builder area and everything will appear. It's a weird issue with css opacity transition in the latest FireFox, which I fixed with some weird css, but it seems to work :)
Looks like we may encounter some more weird issues with css transitions in Firefox - https://forums.envato.com/t/latest-firefox-bug-with-css-scale-transform-opacity-transition/76297
Hopefully they'll fix it in next update.
