### ISSUE TITLE
Content Disappears Aftering Saving

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#1097]
We have had a few reports of this. Customers claim that, randomly, content on the page will be completely wiped out after pressing save. 

**Screencast:**
https://www.screencast.com/t/3cdRoB9AMI8d

**Related Tickets:**
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=666891

**Comment by fikrirasyid** [comment]
@timayhelen I seem to be unable to replicate the issue. Instead of disappearing, I keep getting this failed saving notification:

![1097](https://cloud.githubusercontent.com/assets/916442/24004730/a9a4c8d4-0a99-11e7-9170-4368f1c27c4d.gif)

I've contacted @kary4 and ask for the customer's token. I think something might be specifically different on that site.
