### ISSUE TITLE
Cannot edit sections settings if sections overlap

### ISSUE THREAD

**Issue by websbyjd** [elegantthemes/Divi-Beta#124]
### Problem:

If the sections overlap with negative margin, you are not able to reach edit menu in visual editor.  The UI switches sections before you can get to the menu
![screen-shot](https://cloud.githubusercontent.com/assets/20092710/17823568/2742b012-662b-11e6-939b-47edf80c3c5a.gif)
. 

### Steps To Reproduce:
1. Create two sections
2. give one section negative margin until they overlap (used for various divider styles)
3. try to edit in visual editor
4.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:
PC
**Operating System**:
Windows 10
**Browser**:
Chrome
**Screen Resolution**:

**Screenshots**:

![screen-shot](https://cloud.githubusercontent.com/assets/20092710/17823603/4de6af66-662b-11e6-93b7-7d6a85d50198.gif)

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

**Comment by fikrirasyid** [comment]
The most feasible solution I can think of this issue is created a hotkey for retaining active state (similar to newly added drag padding hotkey). The possible use case is probably: 

1. Hover section / row / module. The hovered element is in active state (has outline and popover).
2. hold `alt` (or other button which is more suitable)
3. As long as the `alt` button is pressed,  the selected element will remains active. Hovering other module will not deactivate currently held active element. This will allow user to access the popover / add new button which is overlapping with other element.
4. once user releases the `alt` key, hover behaviour back to normal again.

This involves design decision as it will affect how the builder work tho. @timayhelen what do you think?

**Comment by timayhelen** [comment]
@fikrirasyid What if when you double click on a module, it opens up the module settings? It doesn't solve the issue completely, but it does solve the main issue of not being able to access module settings.

**Comment by timayhelen** [comment]
I am going to add this to the list of "power user" features, since we already have an issue going for that.
