### ISSUE TITLE
Visual Builder doesn't work with WP 4.6

### ISSUE THREAD

**Issue by jumborexTest** [elegantthemes/Divi-Beta#142]
I have seen a similar bug, but I want to specify that the "Use Visual Builder" shows as expected, but the page I see is a "normal" page: I have found no way to activate the "Visual Builder itself."
I attach an image showing the page visible for the normal users, near the page called clicking upon the "Visual Builder" button.

### Additional Information:

**Operating System**: Windows 10

**Browser**: Edge, Firefox, Chrome

**Screen Resolution**: 1440 x 900

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

![visual](https://cloud.githubusercontent.com/assets/21120636/17830148/5db5a85a-66c3-11e6-8a5c-e6439fa8c7f8.jpg)

**Comment by Bhuvan937** [comment]
Yeah same problem here.

**Comment by SlavaET** [comment]
I see you're using Yoast plugin and it causes the issue, please disable it and check again. This issue with Yoast will be fixed in next version.

**Comment by sosensible** [comment]
**This might be a key difference.** I was trying this out on two sites. One is a multi-site and the other is not of course. The one that it was working on was the multi-site with Yoast still running.

The active plugins on the multi-site are;

- Elegant Themes Divi Beta Tester 1.0
- Elegant Themes Updater 1.0
- Gravity Forms 2.0.6
- Gravity Forms MailChimp Add-On 3.7.1
- Gravity Forms Polls Add-On 3.0
- Gravity Forms Quiz Add-On 3.0
- Gravity Forms Survey Add-On 3.0
- Plugin Toggle 1.2.0
- Yoast SEO 3.4.2

( and since multisite )

- WPMU Assist 1.0.2 ( as must-Use )

**Comment by Bhuvan937** [comment]
Thanks a lot it started working.

**Comment by jumborexTest** [comment]
Waw! Yoast was the problem.
Now a total new world... Thank you Slava

**Comment by Bhuvan937** [comment]
I can't save the changes in Divi Visual Builder.
