### ISSUE TITLE
Error When Loading Some Layouts From Library

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#207]
This error is a bit strange. Basically you need to have the Homepage Extended layout loaded and saved on the page, and then you need to try and load the Homepage Extended layout again. So to reproduce the error, follow these steps:

1. Load the builder. 
2. Load the Homepage Extended layout. 
3. Save the page. 
4. Refresh the page / re-launch the visual builder. 
5. Load the Homepage Extended layout again. 

The following error occurs and causes the builder to break in various ways:

![screen shot 2016-08-26 at 12 29 18 am](https://cloud.githubusercontent.com/assets/3333028/17997666/c7e371d4-6b24-11e6-8e0c-60fa930af83a.png)

**Comment by SlavaET** [comment]
@timayhelen this error appears because Divi tried to load new layout too fast, before all the components properly unmounted.
I changed the layouts loading mechanism to make sure all the components unmounted before loading new layout, it causes some delay when you switch between layouts, but it works and we can be sure that everything was unmounted properly.
When you click on selected layout then Divi will:
1) Remove all the sections from page
2) Update all the **removed** components states ( start showing Preloader at this point )
3) Load new content
4) Update all the **new** components states ( finish showing Preloader at this point )

So starting from step 2 we show the preloader and it appears for 1-2 seconds until everything will be cleared and loaded.

**Comment by timayhelen** [comment]
@SlavaET I think we should use a more "full screen" pre-loader style, like what we use when the app is launched. This way it hides the empty section that appears for a split second during the preloader.

Would it be possible to adjust the preloader in this instance to add a white BG that overlays all of the content, but does not overlay the page settings bar? This way it looks like just the content in the BG is being re-loaded?

We would also want to remove the white circle around the pre-loader in this case, since the background will be white. 

This also makes me wonder about something else. Aren't we currently ajax-loading all library items? If we are going to use an ajax load when loading new "layout" library items, maybe we should also be loading the layout itself via ajax as well, this way we don't need to load all of the layout library items when the tooltip is opened.

**Comment by SlavaET** [comment]
@timayhelen added full screen preloader. As for the loading of each single layout via Ajax on demand - I don't think we'll get significant benefits from this option. Current implementation is most efficient in terms of speed because:
1) We still need ajax request to retrieve the list of all library items and all their metadata. It will be quite fast though
2) Right now loading of any selected layout takes usually 1 second ( sometimes a little more ) and it doesn't depend on the internet connection it only depends on React speed. if we'll use ajax request to load every single layout on demand, then the loading times will depend on internet connection speed and it'll be slower in any case.
3) Currently if you will append the layout ( unselect the "Replace existing content." option while loading the layout ) then it'll work instantly as before and without preloader. It won't be the case if we'll load the layout via ajax.

Do you still think we need to replace current implementation with the loading of layouts on demand?

**Comment by timayhelen** [comment]
@SlavaET Ok, we can keep it the way it is now.
