### ISSUE TITLE
Add Divi Builder Failure Modal

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#233]
I think we should add the same Divi Builder failure modal that we use in the BB to the VB, with one additional warning to "Disable All Browser Extensions" since I think these will more commonly break the VB. 

Can we still detect in the VB fails to load and launch the failure modal?

**Comment by SlavaET** [comment]
Added Failure modal which will appear in case Visual Builder app cannot be loaded ( this should cover most cases when it doesn't load because of plugins )

As for the fails because of low php memory - this is totally unpredictable, because it may break the website loading in different places, for example if I reduce the memory on localhost, then Builder works, but admin-ajax error printed in console. On the websites from our Beta testers it simply stop loading page content in the middle, so Divi scripts were not even loaded.
The only solution I could think of to prevent this issue:
- check the memory limit before loading the Visual Builder and if it's < 128MB, then print error message on screen. If Builder scripts will be loaded, then Failure Modal will appear, otherwise error message will stay printed on the screen and users will see the error in any case.
The only drawback of this solution - we'll force all the users to increase memory limit to 128MB.

@timayhelen what do you think?

**Comment by timayhelen** [comment]
@SlavaET What if we re-consider the idea of bumping up the memory limit to 128mb automatically?

@Jronk @uportnykh what do you think?

**Comment by SlavaET** [comment]
I think we can do that, if it's normal practise to silently update the php settings. In case if it's not allowed by server settings we can fallback to solution I proposed and ask user to manually increase the memory limit.

**Comment by timayhelen** [comment]
Ok, let's just silently update to 128mb if the current limit is < 128mb. We can forgo the warning for now. We can add it later if it's still causing issues.

**Comment by SlavaET** [comment]
@timayhelen done. It works as follows now:
- Display our Failure Modal if app cannot be loaded.
- increase the memory limit to 128MB silently If it less than 128MB. Do not generate any warnings if memory increasing fails. In some cases memory issue may trigger `app cannot be loaded` and Failure modal will be displayed.

You can emulate the `app cannot be loaded` error and see the Failure modal in action by replacing this code:
```
return sprintf( '<div id="et-fb-app"%1$s></div>', $class );
```
with
```
return sprintf( '<div id="et-fb-app1"%1$s></div>', $class );
```
in the `/includes/builder/frontend-builder/view.php` file.
