### ISSUE TITLE
Modules disappear on front end page  / reappear when VB is on.

### ISSUE THREAD

**Issue by MyInternetScout** [elegantthemes/Divi-Beta#236]
### Problem:

After making adjustments to the test site's home page with the visual builder, various modules stopped appearing on the published page.  The modules I was moving around disappeared as well as modules that weren't even touched during the edit session.  The bars of the animated counter module also disappeared.

When I go to back-end to edit the page, all of the modules are there as the should be.  Then, when I go to the front end and use the visual builder, the modules reappear.  Once I exit the VB again, the modules disappear again.  

### Additional Information:

**Laptop**:

**Windows 10**:

**Chrome and MS Edge**:

**1600x900**:

![20160830 vb off - missing modules](https://cloud.githubusercontent.com/assets/21134596/18088283/d565a9a6-6e87-11e6-8019-bc4030c37bf3.jpg)
![20160830 vb on -missing modules](https://cloud.githubusercontent.com/assets/21134596/18088285/d8bd9b40-6e87-11e6-8a0c-178ba5a63332.jpg)

**Comment by fikrirasyid** [comment]
@MyInternetScout thank you for reporting the issue. Can you export the layout using portability feature, zip it, then attach it here? It'll greatly help us to debug the issue. Thanks!

**Comment by MyInternetScout** [comment]
Hi @fikrirasyid 

My issue just become more complex.  I'm unable to save the layout because there's a split test in progress - which I completely forgot about.  I attempted to turn off the split test (so I can save the layout for you), but the split test popup is blank (refer to enclosed screenshot).   I'm now cataloging three issues.  the modules are missing, the split test can't be turned off, and the layout can't be saved.   - Peter
![20160830 unable to turn off split test to save layout](https://cloud.githubusercontent.com/assets/21134596/18093881/6f245ff8-6e9f-11e6-82c3-5c8c4d2f1450.jpg)

**Comment by fikrirasyid** [comment]
@MyInternetScout can you try exporting the layout using VB?

**Comment by MyInternetScout** [comment]
I was able to export the layout using VB.  I've enclosed the zipped .json file.  
[Divi Beta MIS homepage layout.zip](https://github.com/elegantthemes/Divi-Beta/files/445316/Divi.Beta.MIS.homepage.layout.zip)

**Comment by fikrirasyid** [comment]
@MyInternetScout Thanks! We're currently investigating the issue

**Comment by fikrirasyid** [comment]
@MyInternetScout I've tried to replicate the issue but it works as expected on my local installation. However, based on your screenshot I noticed several differences. Can you do the following:

1. List all active plugin you use
2. List all browser extension you use
3. Try deactivate all of your active plugin and see whether the issue remains or not

Since the issue cannot replicated on clean installation and you appear to use cache plugin, my best guess is this issue caused by cache: modules appear on VB but it doesn't appear on VB. It might be caused by the cache that doesn't get flushed when the layout is saved. To confirm this possibility, please do three steps above. Thanks 😄

**Comment by fikrirasyid** [comment]
As in these other issues:

- the split test can't be turned off
- and the layout can't be saved.

Can you open the browser's console (right click, open the `console` tab) then re-do the process? Please inform me the error message you found on the `console`.

**Comment by MyInternetScout** [comment]
I've turned off all plugins and issue persists.  Turned off all extensions in Chrome and issue persists.  I tested the page on the Windows 10 Edge and Firefox browsers, and the issue persists.  Feel Free to visit the page at http://staging.myinternetscout.net/preview

**Comment by fikrirasyid** [comment]
@MyInternetScout I've checked out your preview site. It appears that the missing module happened because of this : ![screen shot 2016-08-31 at 11 01 55 pm](https://cloud.githubusercontent.com/assets/916442/18136404/7177e884-6fcf-11e6-8401-9b325af5b09a.png)

The error message above appears because:

1. Your site has cache plugin
2. Your site has a/b testing running
3. Front end's script triggers a/b testing function but it cannot find any a/b testing subject 

Thus, please try the following: 

1. Disable the page's ab testing, then see the page again.
2. Since you mentioned that there's an issue with BB too, try creating new page and importing the same layout.

**Comment by MyInternetScout** [comment]
okay.  I imported the layout into a new page and the page loads as it's suppose to - and a/b testing is currently off.

**Comment by fikrirasyid** [comment]
@MyInternetScout alright, it confirms that somehow the layout is unintentionally edited and corrupt the layout. It is kinda hard to determine the cause of the change tho; it can be previous beta version of VB, or something happens on BB, or else. What we can do is anticipate the VB to still working even if the layout is corrupted due to unintentional setting. Can you do the following, so we can get the layout without exporter normalization: 

1. I just checked http://staging.myinternetscout.net/ and it appears without the issue, so I assume the homepage uses the exported layout. So:
2. Open the old page layout
3. Click edit page on the admin bar
4. On the editing page (backend), right click then select `inspect`
5. Select `console` tab. Wait a second or two.
6. Type this: `jQuery('#et_pb_main_editor_wrap').show();` then hit enter
7. The shortcode will appear. Copy and paste the shortcode on this thread.

Here's a visual guidance on what to do:

![exporting-raw-shortcode](https://cloud.githubusercontent.com/assets/916442/18192141/a70c56b0-70fb-11e6-9c53-f02c782497e6.gif)

Thanks!
