### ISSUE TITLE
Save and Load from Library

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#267]
### Problem:

Creating and save a module ( I did test it with Text Module) to my library using FB and then on another row trying to import that module, doesn't work. I have to exit the FB then load it again, to see my saved modules.

### Steps To Reproduce:
1.  save a module (text module) to the library from FB
2. try to load that module into another column

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**: desktop

**Operating System**: mac os x

**Browser**: Chrome

**Screen Resolution**:

**Screenshot or Screencast**:
https://drive.google.com/file/d/0B8PjD3Z_XQvudTRiaGI3aXVGZDA/view?usp=sharing

**Comment by timayhelen** [comment]
I think this is a duplicate issue, and Slava has fixed it. Basically it occurs when adding new library items into an empty row. Thanks!

**Comment by SlavaET** [comment]
@timayhelen It's a different issue actually. As far as I understand Eduard has clicked `Add New` modal and all the library items were preloaded. Then he saved the new item into library and open `Add New` modal again. This time the item he just saved will not appear, because library items were preloaded earlier. 
It's the same as in BB actually - you need to refresh the page to see newly saved items.
To improve it we can check whether the item was saved from VB and reload library items if that happens.

**Comment by eduard-ungureanu** [comment]
@SlavaET that was exactly what I did. Just tried with a simple refresh now instead of exiting / entering the Visual Editor again, and my new items did appear.
