### ISSUE TITLE
First Time Opening Tooltip Causes Horizontal Shift

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#292]
Load the visual builder and click an "add section" button to trigger the tooltip modal. This first time it opens, you will see that it triggers a horizontal content shift for a split second. It doesn't happen again after that.

**Comment by fikrirasyid** [comment]
@timayhelen can you elaborate more on what do you mean by "horizontal shift"? I assume what you mean is either the module or window has horizontal scrolls, but neither of them appears to happen. 

This is how the hovering tooltip for the first time appears on my localhost. It looks like expected tho:

[292-fix-first-time-opened-tooltip-causes-horizontal-shift.zip](https://github.com/elegantthemes/Divi-Beta/files/451719/292-fix-first-time-opened-tooltip-causes-horizontal-shift.zip)

**Comment by timayhelen** [comment]
Basically the entire page shifts over like 20px for a split second, then goes back to normal. You have to look carefully right when you click the (+) button for the first time. It's hard to capture in a GIF.

**Comment by fikrirasyid** [comment]
Ah I see. I can replicate the issue now. I thought you're referring to this tooltip:

![screen shot 2016-09-02 at 5 05 48 pm](https://cloud.githubusercontent.com/assets/916442/18200576/99158a34-712f-11e6-802a-c8a2f3633286.png)

It turns out that you're referring to this tooltip:

![screen shot 2016-09-02 at 5 05 40 pm](https://cloud.githubusercontent.com/assets/916442/18200581/a542b926-712f-11e6-8f5a-910f810c691c.png)

I think we need a different term for one of them 😅

**Comment by timayhelen** [comment]
Ah yeah, haha.
