### ISSUE TITLE
Fixe Responsive Previews & Zoom Out in Divi Builder Plugin and Extra

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#316]
@SlavaET Can you take a look at this? Maybe we can hide all theme content, similar to what we do on Divi posts with sidebars. 

FYI there are currently branches open in both Extra and the Divi Builder repos that should be used along with each 1848 submodule branch.

**Comment by SlavaET** [comment]
@timayhelen since we cannot predict the HTML structure of 3rd party themes I decided to go a different route. Instead of hiding all the content we will just output overlay which will sit on top of the all content ( with `z-index:999999;` )  and our app will sit on top of that overlay with `z-index: 9999999;` which will create the effect we need.

**Comment by SlavaET** [comment]
Oh, wait, I think I found an issue there. Working on it.

**Comment by SlavaET** [comment]
Ok, now it's ready. 
Please note there is a PR for Divi theme as well - https://github.com/elegantthemes/Divi/issues/2521

**Comment by timayhelen** [comment]
@SlavaET Looks like the responsive overlay Divi get's re-added and stacked every time you click one of the responsive preview icons. 

I wonder if we should position the builder content absolutely and center it horizontally? The experience isn't ideal on themes with small content areas and sidebars.

**Comment by SlavaET** [comment]
@timayhelen fixed the issue with adding of multiple overlays and improved the positioning of app in responsive preview mode for different themes.
