### ISSUE TITLE
Possible Conflict With Ninja Forms

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#390]
From the forums:

> Site URL: www.desino.dk
> WordPress Version: latest
> 
> Hi guys,
> 
> So i just tried to update to 3.0 and all was good, until i wanted to try the frontend edit option.
> 
> Then i got notice about a plugin is creating a conflict.
> 
> So found that my ninjaform plugin
> 
> https://ninjaforms.com/
> 
> is the one that conflict... so any ideas on how to solve this?
> 
> Thx 
> Martin

**Comment by Jronk** [comment]
Can we ask for what was said in the "notice"?

**Comment by timayhelen** [comment]
I think he is referring the builder failure notice.

**Comment by fikrirasyid** [comment]
@timayhelen can you post the thread url? I tried replicating the issue (all plugins disabled except for ninja form) but it doesn't trigger the failure modal. It fails parsing the shortcode tho, so for the time being I'll start with it.

**Comment by fikrirasyid** [comment]
Turns out the `parsing failure shorcode` unveils a flaw in our current shortcode parsing mechanism. I've improved it on https://github.com/elegantthemes/submodule-builder/pull/1144.

**Comment by timayhelen** [comment]
@fikrirasyid Can we add our pre-lodaer animation at the location of the shortcodes while the 2000ms is occurring? Also, are we sure 2000ms is necessary?

**Comment by fikrirasyid** [comment]
@timayhelen it will be a little bit tricky to add pre-loader while waiting for the parsed shortcode to load, but I think it'll improve the UX. I'll take a look at this.

The 2000ms is necessary. The issues are:

1. When the iframe is loaded, it only contains the pre-loader. Without the timeout, we'll fetch this pre-loader instead of the modified DOM
2. There are no fixed standard on how shortcode is modified by JS. In a ideal situation, i would like to use callback after a JS done modifying shortcode's DOM but unfortunately there's now exact way of doing so. There are way too many shortcodes and way too many variation of how they are being modified. The best approach that I can think of right now is assume that most shortcode will be done modified by JS in 2000 ms.
