### ISSUE TITLE
Possible Issue With Boxed Layout

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#416]
I see several reports of "content sticking to the left of the screen." In each screenshot, they were using a boxed layout. Could be a coincidence, but let's investigate.

**Comment by Anny85** [comment]
@timayhelen I was able to replicate the issue. You can try to open a module settings modal and then close it.

**Comment by timayhelen** [comment]
@Anny85 The error still occurs if you snap modal to the right of the screen:

![snap](https://cloud.githubusercontent.com/assets/3333028/18365027/c24fa2c8-75c5-11e6-8150-5829a964577c.gif)

**Comment by Jronk** [comment]
The issue would occur if you dragged the modal, or snapped it, now it will leave the `#page-container` margin left and right alone if boxed layout is enabled since the content is already out of the way of a snapped modal.

![boxed-layout-modal-snapping](https://cloud.githubusercontent.com/assets/1163441/18370050/c28ba282-75de-11e6-8164-27f87e4d3c4e.gif)
