### ISSUE TITLE
Don't Keep Retrying Ajax Requests That Return "0"

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#419]
### Problem:

I noticed the Ajax request for retrieving premade layouts keeps retrying constantly even when the result is "0". A result of "0" is not likely to change until whatever is causing it is fixed/adjusted on the server so there is no need to keep retrying. Instead, we should display the failure modal and let the user know that the VB is unable to communicate with their server and thus all features which rely on communicating with the server will not work (including saving the page).

**Comment by SlavaET** [comment]
@lots0logs I don't think we should display the failure modal in that case because we cannot tell for sure whether it's a global issue or something went wrong during the particular request or if something went wrong in a local function. So I think we should keep our current error handling, but fix the error with ajax requests loop while loading library items ( I checked all other ajax requests and "0" response situations handled properly there ). 
So if we received wrong response during the library items retrieval we will output appropriate error message and will not try to retrieve the items again.

@timayhelen you may want to adjust the wording of error message here - 
https://github.com/elegantthemes/submodule-builder/pull/1150/files#diff-a9a0a716113f80a4e7cd5cfc029f9761R556
