### ISSUE TITLE
Text module :: Color picker :: can't add hex color

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#423]
### Problem:

When I try to input #fff the color picker doesn't change the value

![animation](https://cloud.githubusercontent.com/assets/9657712/18381334/8b1646c6-769d-11e6-9b60-8024fc2e0461.gif)

### Steps To Reproduce:
1.  Select text 
2. Open color picker
3. Try to input hex color #fff
4. 

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by SlavaET** [comment]
@andrey-agp what if you input `#ffffff` will it work?

**Comment by andrey-agp** [comment]
@SlavaET no, it doesn't change the value when I type, it doesn't allow to change the value.

**Comment by fikrirasyid** [comment]
I'm still working on this; I finally understand the issue but haven't found a decent solution yet, I typed what I know for the time being for future reference:

- The issue happens due to inline editor's colorpicker uses module setting's color picker
- module settings colorpicker is made under assumption that it updates module's attribute
- inline editor doesn't update any module's attribute. It updates the content's text instead

So basically there are four mechanism that needs to be validated:

- module settings > colorpicker > updating via the colorpicker works.
- module settings > colorpicker > updating via input text works
- inline editor > colorpicker > updating via colorpicker works
- inline editor > colorpicker > updating via input text doesn't work. As you type, the typed string is validated by both colorpicker's color validation AND tinyMCE's color validation. This makes inserting via input text impossible because as you type `#9` the typed string becomes validated into `rgb(255,255,255)` and you can further type the next string.

I'm still working on it. I'll update this thread once I found a decent solution.

**Comment by timayhelen** [comment]
@fikrirasyid There is a second issue related to this, which affects the color picker in the settings modal. Basically every time you enter 3 hex decimal characters, it auto-completed the remaining 3 characters and often does a bad job guessing what you are trying to type in. This makes it impossible to type in certain colors unless you copy and paste the 6 digits in directly.

**Comment by fikrirasyid** [comment]
@timayhelen yeah, that is what I'm discovering as well. Basically tinyMCE automatically guess the 6-digits hexacode equivalent of the typed 6-digits hexacode. The issue is in inline editor, it double sanitize the typed value (wpColorPicker and tinyMCE). I'm still looking a way to fix it properly.

**Comment by timayhelen** [comment]
@fikrirasyid I actually remember this issue occurring in the BB, and we must have fixed it somehow because it doesn't happy anymore.

**Comment by fikrirasyid** [comment]
@timayhelen I've submitted a patch at https://github.com/elegantthemes/submodule-builder/pull/1168

**Comment by timayhelen** [comment]
@fikrirasyid This PR seems to break the color picker when apply colors normally, when you first click into a module. But after I switch modules and come back, it starts working:

![color](https://cloud.githubusercontent.com/assets/3333028/18492028/167c0f66-79be-11e6-936e-3542cf8945a8.gif)

**Comment by fikrirasyid** [comment]
@timayhelen I've investigated and fixed the issue at https://github.com/elegantthemes/submodule-builder/commit/d284334f9ddd32be146b58a7783e13b0d86d1eb9.
