### ISSUE TITLE
Visual builder: Module Settings Box overlap the text

### ISSUE THREAD

**Issue by OlgaT** [elegantthemes/Divi-Beta#431]
### Problem:

When you click on a text module to edit it, module settings panel overlaps the some words 

![screen shot 2016-09-08 at 9 16 34 am](https://cloud.githubusercontent.com/assets/7305702/18398308/0af0cbb4-76ee-11e6-93ae-6386fc45e06d.png)

**Comment by timayhelen** [comment]
@OlgaT Are you using Divi 3.0.1?

**Comment by OlgaT** [comment]
@timayhelen Yes. I can't change style 2or 3 words, because it's hard to define it with the mouse. I attached another screenshot. I should move the mouse athe very bottom of the module settings panel. It's not a big issue, but cistomer said that it's very annoying
![screen](https://cloud.githubusercontent.com/assets/7305702/18412155/e2724944-77a9-11e6-8648-6efc54f7ad2a.jpg)

**Comment by OlgaT** [comment]
https://www.elegantthemes.com/forum/viewtopic.php?f=21&t=589876

**Comment by lots0logs** [comment]
@OlgaT Could you confirm that this issue still exists in the latest version (3.0.2)?

**Comment by OlgaT** [comment]
@lots0logs 
![screen](https://cloud.githubusercontent.com/assets/7305702/18446990/7c930386-7946-11e6-8cc5-44f3e014ecb8.jpg)
Yes

**Comment by lots0logs** [comment]
@OlgaT Did you try clicking in the text to activate the inline editor? The settings bars should move out of the way.

**Comment by lots0logs** [comment]
@SlavaET Can we make the settings bar appear outside the module when the inline editor is active so it doesnt cover any text?

**Comment by timayhelen** [comment]
I think we can just remove row and section button groups when the inline editor is active + the mouse is hovered over the module with the inline editor active.

**Comment by timayhelen** [comment]
- Is it possible to avoid the flashing in/out of section and row button groups when clicking into different modules?

![flash](https://cloud.githubusercontent.com/assets/3333028/18491733/ac66fd26-79bc-11e6-9ad4-d8e4346a12ea.gif)

- Can we make it so that Section/Row buttons and outlines still appear normally when you hover outside the current module being edited with the inline editor?

- If you click into a TincyMCE area that triggers the popover, and then click into another editable areas in the same module that does not trigger the popover, parent module and row buttons appear and it covers up the text area:

![switch](https://cloud.githubusercontent.com/assets/3333028/18491811/11e8de3a-79bd-11e6-9c3c-418f85886f6f.gif)

**Comment by SlavaET** [comment]
@timayhelen fixed issues №2 and №3 as for the №1 from your list it's quite opposite to №2 though effect is little different now if you move the mouse out of module which is being edited then all the Row and Section controls will appear and it will create that flashing effect. Please take a look at the updated PR and let me know if you see any issues there.

**Comment by eduard-ungureanu** [comment]
this issue also related to the text module, but in a slightly different context, please check out this video screen cast:

https://drive.google.com/file/d/0B8PjD3Z_XQvuNjJzU2FFM2YxMFE/view?usp=sharing
