### ISSUE TITLE
Improving Draggable Height & Width Usability

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#433]
A few ideas for improving the experience:

1. Holding Alt While Dragging:  Limits the current padding to < or = it's opposite padding. So for example, if you have dragged a padding-left out to 100px, and you hold alt and drag the padding-right, it stops at 100px. This way you can quickly make both paddings the same. 
2. Holding Shift+Alt while dragging: Drags the opposite padding at the same rate. This way you can drag out padding-top, and it will mirror the value at padding-bottom. 
3. Holding Shift While Dragging: Limits the padding value to increments of 10. So it will snap to 10px, 20px, 30px or 10%, 20%, 30% etc.
4. Adding Units Indicator: We need to add an indicator of units while dragging. I think it can just be centered vertically/horizontally inside the padding overlay.

**Comment by timayhelen** [comment]
@fikrirasyid This is looking great! A couple things we can improve:

1. It looks like there is a stutter now when the padding indicator fades it. Instead of being smooth, it  fades it to about 10% and then jumps the rest of the way without a smooth transition:

![smooth](https://cloud.githubusercontent.com/assets/3333028/18564289/bbac442e-7b3f-11e6-8d4c-98f07e023e7b.gif)

2. I think we only need to display numbers while dragging. So can those fade it after dragging occurs? (it would be nice to have them fade instead of appear instantly)

**Comment by fikrirasyid** [comment]
@timayhelen noted. I'll adjust it 👍

**Comment by fikrirasyid** [comment]
@timayhelen I've updated the way animation works on drag padding indicator. It looks smooth now:

 ![smooth like santana](https://cloud.githubusercontent.com/assets/916442/18574816/cbdb44b0-7bfa-11e6-8778-612519af8c83.gif)

**Comment by timayhelen** [comment]
@fikrirasyid It looks like there is no longer a delay for row and section outlines and padding indicators. Previously there was a hover-intent delay on these elements.

**Comment by timayhelen** [comment]
@fikrirasyid use of React Motion also resulted in some glitchiness when adjusting padding. It seems to jump all around while you drag and it's smooth like it used to be:

Before:

![before](https://cloud.githubusercontent.com/assets/3333028/18600597/5eec1c26-7c13-11e6-8885-d9822621bf6d.gif)


After:

![after](https://cloud.githubusercontent.com/assets/3333028/18600594/5b195f8c-7c13-11e6-89ee-e1e6e3fc7524.gif)

**Comment by fikrirasyid** [comment]
@timayhelen can you take a look at https://github.com/elegantthemes/submodule-builder/pull/1182 again? I ended up replacing react motion for fadeIn effect with simple CSS transition because React Motion appears to screw the timing on the padding bottom's indicator if it is being used. This is how it looks now:

![smooth-padding-bottom-change](https://cloud.githubusercontent.com/assets/916442/18780675/efb6c66c-81a8-11e6-84a5-9fd2ea004d63.gif)

Regarding this:

> @fikrirasyid It looks like there is no longer a delay for row and section outlines and padding indicators. Previously there was a hover-intent delay on these elements.

Can you take a look at `/frontend-builder/app/assets/css/style.css` file? I was quite confused because as far as I can remember, there's no intended delay. I somehow noticed that there's this clunky lag. After investigating it, I remember that a while ago I run production build which generates `style.css` being made and stored at `/frontend-builder/app/assets/css/style.css` path. This file doesn't get removed when I run dev build (`npm start`) and end up causing unintended effect (dev build doesn't generate `/frontend-builder/app/assets/css/style.css` to speed things up).

**Comment by timayhelen** [comment]
@fikrirasyid There was intended delay on all outlines and padding indicators. You can test out master to see. It looks like you did it by simply have the first 70% of the CSS animation do nothing.

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed the CSS animation to emulate the hover-intent mechanism
