### ISSUE TITLE
Visual builder: section/row/module panels chang color to the custom

### ISSUE THREAD

**Issue by OlgaT** [elegantthemes/Divi-Beta#436]
When you change the button background color in Extra > Theme customizer > Buttons > button styles
 all panels became the one color. I attached the customer's screenshot, but I can replicate it on my own instalation.
![screen](https://cloud.githubusercontent.com/assets/7305702/18412279/41500e68-77ac-11e6-9b0c-bf311cd3db74.jpg)
![screen shot 2016-09-07 at 8 28 11 pm](https://cloud.githubusercontent.com/assets/7305702/18412278/414e4984-77ac-11e6-993d-839d561122da.jpg)

**Comment by SlavaET** [comment]
@timayhelen I see that button settings in Extra theme affects all the buttons on page ( it's different than in Divi ). Isn't it supposed to apply these settings to custom buttons only? Is it intentional that we have this selector for buttons styles in Extra:
```
'#page-container button',
```
Or do we need to target specific areas and can use more precise selector?
I want to clarify because if we can change this selector, then it'll fix the issue. Otherwise we need to use more precise selectors ( or `!important` tags ) for Visual Builder's buttons.

**Comment by timayhelen** [comment]
@SlavaET I think we should fix this in the visual builder.

**Comment by timayhelen** [comment]
@SlavaET The new buttons styles overwrite other buttons styles in the VB. For example, Fullwidth Section button colors and Speciality Section button colors.

**Comment by SlavaET** [comment]
@timayhelen fixed.
