### ISSUE TITLE
"Load from library" modal doesn't translate predefined layout names

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#442]
### Problem:

Should predefined layout names be translated? I see retrieving translation of that names in the code but don't see any translations in the po and mo files.

**Comment by Anny85** [comment]
@timayhelen Predefined layouts are being imported, if they don't exist or the import is forced. So if a user switches to another language and predefined layouts are imported after that, everything should work fine. 

I think we don't want to force predefined layouts to update, when a user switches to another language, since there might be some issues with multilingual sites running WPML. Predefined layouts might be updated many times in such case.

What do you think?

**Comment by timayhelen** [comment]
Ok let's not worry about it. But translations are being correctly applied to the VB?

**Comment by Anny85** [comment]
@timayhelen Yes, translations are being applied correctly in all other areas.
