### ISSUE TITLE
Updraft Plugin Causes VB Changes To Not Save

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#444]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=589303

**Comment by SlavaET** [comment]
Cannot reproduce this issue.
I tried installing the `UpdraftPlus` plugin, since `Updraft` which I see in the list of available plugins wasn't updated for 6 years and it throws an error in admin when installed.
Probably they're talking about different commercial plugin which is no listed in the WP Plugins directory.

**Comment by lots0logs** [comment]
@SlavaET I think you installed the wrong plugin. Usually when people say Updraft they are referring to UpdraftPlus
