### ISSUE TITLE
Plugin compatibility :: WPMU Hummingbird

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#477]
### Problem:

When the plugin is enabled you cannot  modify padding under section module settings, or in the front end builder page. 
Screen cast: http://youtu.be/fSjWQ3nrBT0?hd=1

Plugin: https://premium.wpmudev.org/project/wp-hummingbird/?utm_expid=3606929-84.YoGL0StOSa-tkbGo-lVlvw.0&utm_referrer=https%3A%2F%2Fpremium.wpmudev.org%2Fblog%2Fhummingbird%2F

It's a paid plugin, so unfortunately I can't check it locally, but I was able to check the problem on the user's website here: https://divi.vincentsolutions.ca
token: Z!fY6h7te@wO2GDMR

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=190&t=591550&p=3270694#p3270694

**Comment by SlavaET** [comment]
The root cause if the issue is in order of styles loading on the page. Hammingbird plugin changes the order of styles loading and padding defined for the Sections and Rows in Customizer settings overrides custom padding defined in the Rows and Sections directly.
The solution - use more specific selectors for the Row and Section custom padding. 
So, in my PR I changed the selectors from this:
`.et_pb_row_0` and `.et_pb_section_0`
to this:
`.et_pb_row_0.et_pb_row` and `.et_pb_section_0.et_pb_section`
And it'll have higher priority than the styles defined in Customizers regardless the order.

**Comment by kary4** [comment]
The customer posted a solution from WPMU Hummingbird support:

So WPMU Devs figured it out, they had me add something to functions.php of my child theme and it works now with Hummingbird ! 

Here is the code if anyone needs it in the future : 


```add_action( 'after_setup_theme', 'remove_divi_hummingbird_hooks', 1 );
function remove_divi_hummingbird_hooks() {
	remove_action( 'after_setup_theme', 'wphb_divi_after_setup_theme' );
}
```
