### ISSUE TITLE
Text module :: center alignment on responsive preview

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#483]
### Steps To Reproduce:
1.  create row
2.  change gutter width to 1 in row settings
3.  create text module and change Text Orientation option to center 
4. in module advanced settings set custom width 50%
5. check responsive preview

![screenshot_2](https://cloud.githubusercontent.com/assets/9657712/18606594/31741de8-7cd6-11e6-85c0-10b72c6e6806.png)

how it should look 
![screenshot_3](https://cloud.githubusercontent.com/assets/9657712/18606608/854a2c28-7cd6-11e6-8ded-c6280cf5702b.png)

Same issue happens on desktop preview in VB and on the page itself.

### Additional Information:

*Please include any of the following details that are relevant to the issue you are reporting.*

**Device**:

**Operating System**:

**Browser**:

**Screen Resolution**:

**Screenshot or Screencast**:

**Link To Download Layout JSON File**:

-

#### Before submitting your issue, please ensure the following:

* You searched this Github repo for the issue and found no open reports of the issue.
* You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
* You have provided a detailed description of the issue.
* You have provided any/all relevant information: screenshot, screencast, page URL.
* You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
@fikrirasyid We need to add styles for `right` and `justified` alignments as well.

**Comment by fikrirasyid** [comment]
@lots0logs There's this thing tho: It appears that the adjustment only happen on center alignment and actual front page looks identical at https://github.com/elegantthemes/submodule-builder/pull/1229:

## Desktop
![483-desktop-actual](https://cloud.githubusercontent.com/assets/916442/18873892/b66cd586-84eb-11e6-8ff9-a5aa54b9c831.jpg)

![483-desktop-vb](https://cloud.githubusercontent.com/assets/916442/18873891/b66c7640-84eb-11e6-8535-c1cd5688dfa5.jpg)

## Tablet
![483-tablet-actual](https://cloud.githubusercontent.com/assets/916442/18873903/c4248764-84eb-11e6-860f-a11dda4000a4.jpg)

![483-tablet-vb](https://cloud.githubusercontent.com/assets/916442/18873904/c48df276-84eb-11e6-88fa-3296874cc8f9.jpg)


## Phone
![483-phone-vb-actual](https://cloud.githubusercontent.com/assets/916442/18874715/f09b315c-84ec-11e6-8be0-e25bdc69770c.jpg)

***

Thus, there is two possibility:

1. it is intentional that the adjustment only happens on center alignment. (If this is the case, the PR at this stage is correct)
2. The actual front-end's alignments need to be fixed as well.

@timayhelen can you clarify this?
