### ISSUE TITLE
JS Error Starting WIth Divi 3.0.5

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#485]
The following error is occurring on this website:

http://www.pianowizardacademy.com/

Error:

<img width="731" alt="screen shot 2016-09-17 at 4 18 03 am" src="https://cloud.githubusercontent.com/assets/3333028/18607848/d91f3080-7c8d-11e6-8119-290f5800d0b8.png">

The line in question seems to be related to A/B Testing.

**Comment by timayhelen** [comment]
Update from the user. Apparently they had run a split test in the past, but it had since been completed. However, they tried deleting the module that had been split tested in the [ast, and it fixed the error.

**Comment by SlavaET** [comment]
@timayhelen I cannot reproduce the issue locally, I suppose it happend because the Split Test wasn't finished correctly and not all the Testing attributes were cleared. I improved the code though, to avoid such error.
btw, I'm not sure it's even related to Divi 3.0.5, because this code wasn't changed there in any way, so this issue was there before 3.0.
