### ISSUE TITLE
"Hide Nav Before Scroll" Doesn't Work In VB

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#503]
This option, found in the Divi Page Settings meta box when editing a post, does not work correctly in the VB.

**Comment by timayhelen** [comment]
This seems to be a different root issue. I can't replicate now, possibly some random JS error.

**Comment by arc909** [comment]
I'm also getting this with release build version: 3.0.40 on my site http://www.ancpl.com

This happens when my home page has one full width section with one full width header. If I add a second full width header and a full width section (set to defaults) the primary menu no longer appears even when scrolling down.

If I retain my original full width header and full width section (with primary and secondary buttons) but then add a blank standard section with one column then the primary menu appears when scrolling down. If I remove the one column row then the primary menu does not appear when scrolling down.

If I retain my original full width header and full width section and add a blank speciality section then the primary menu also appears when scrolling down.

I'm now using a work around with my original full width header and full width section and a blank standard section a row and a divider.
