### ISSUE TITLE
Changes Aren't Saved Correctly When Initiating VB From An Unsaved "Preview"

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#506]
1. Create a new page.
2. Enable the Divi Builder
3. Load a layout. 
4. Do not save the draft, and click "Preview"
5. Enable the Visual Builder from the front-end preview. 
6. The VB launches correctly with the layout loaded. However, if you make any changes and then save the draft in the VB, the page will not be saved and you are left with a blank page when you check the BB.

**Comment by Jronk** [comment]
The problem comes down to this:
1. Start page in BB (new or existing page)
2. You open new tab, via preview or even via "Use Visual Builder" button using "open in new tab"
3. Enable FB in the new tab (if not already enabled) 
4. Make changes and save
5. The content in BB is now obsolete, and if you were to hit save, you would overwrite the last saved FB from step 4.

Solution, is to have BB checking for changes, and if detected, then it needs to refresh its content.

This is a new "problem" in WP, as the post lock is its std way of preventing two editors editing the same post allowing one to stomp the other. WP's approach is to stop you from editing in the second editor instance, whereas our desired UX would be to allow the FB to make the changes and let the BB (which is in the background anyways since you are editing via FB at the moment)  silently and simply catch up to latest content. Since we "own" both the FB and BB we can define how they interact/depend on each other.

What you see below is a change made to the FB on right, saved in FB, then the BB on left is automatically refreshing its content (via ajax not page refresh).

![fb-changes-to-bb-sync](https://cloud.githubusercontent.com/assets/1163441/18964448/cd4b1658-862d-11e6-8eed-bf8ae8353323.gif)

**Comment by lots0logs** [comment]
>Currently, the BB is set to poll the server every 5 secs to check if changes have been made.
That will likely cause problems on low-quality hosting plans (depending on how often the builder is used). Also, we need to keep in mind that roundtrips to the server can take much longer on shared hosts--especially when the server is under high load (4-10 seconds is not uncommon based on what I've experienced on customer sites)

**Comment by timayhelen** [comment]
@lots0logs I talked with Josh about this already. We are going to tap into the normal WP heartbeat instead, so it shouldn't add much extra load and people who have configured it to be slow will still run smoothly.

**Comment by Jronk** [comment]
Elegant themes + WordPress = Our Heartbeats together ❤️
