### ISSUE TITLE
 Revolution Slider Display Incorrectly in Visual Builder

### ISSUE THREAD

**Issue by andreisnoopy** [elegantthemes/Divi-Beta#513]
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=594726

**Comment by timayhelen** [comment]
This same thing is happening for some people using Layer Slider.

**Comment by fikrirasyid** [comment]
@andreisnoopy can you ask the customer to export his/her slider and attach it here? I was trying to replicate the issue by installing the copy of revolution slider we have and good lord I don't know how to use this thing. So many configuration 😩 Also, which version of revolution slider the customer using? Mine is stuck at version `5.0.x.x` which is bundled by X theme we used for builder comparison during 3.0 development

@timayhelen do we have a copy of layer slider so we can test it out?

In general, shortcode support in VB is really limited at this moment due to various way shortcode is rendered. In most cases, especially shortcode which is JS-centric, the shortcode isn't functional. However we tried our best to make it visually acceptable, pretty much like rendered `[gallery]` in WordPress' visual editor. For more details, see: https://github.com/elegantthemes/submodule-builder/pull/1144

**Comment by andreisnoopy** [comment]
@fikrirasyid  Sorry for the delay ! I think I've missed the notification from this topic. The client never replied on that ticket, I will send him a PM and ask if the issue is still there.
