### ISSUE TITLE
Call To Action :: Clear color

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#514]
### Problem:

Clear color button doesn't work
![animation](https://cloud.githubusercontent.com/assets/9657712/18703096/464a077c-8006-11e6-9aae-e288b21e6435.gif)

### Steps To Reproduce:
1.  Create CTA and change background color
2. Save module
3. Open module again and click Clear 

Same issue for header color and body color in advanced desing settings.

**Comment by fikrirasyid** [comment]
@andrey-agp  can you take a look at https://github.com/elegantthemes/submodule-builder/pull/1226?

**Comment by lots0logs** [comment]
@fikrirasyid Clearing the color should result in the theme's default color for the element being applied. That's how it works with the BB (although its obviously more complicated for the FB since we are showing the color change live).

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated your feedback at https://github.com/elegantthemes/submodule-builder/commit/513626fd51f1bd10236f169a0789f3ce5bbb94f2. There's this one issue about this tho: not all field has `default` / `shortcode_default` value (which is configured at `main-modules.php`). If no default value found, clear will just simply "clear" the value (instead of replacing it with default data)
