### ISSUE TITLE
Ctrl/cmd+z erase all text which was written on one line

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#519]
### Problem:

When you write a long text on one line, using the ctrl/cmd+z key will erase everything without a possibility to return the text back. A customer was very frustrated with this.

This is a screenshot when I made a mistake writing "cat" instead of "car". Using the ctrl+z can be catastrophic in some cases!

![r1](https://cloud.githubusercontent.com/assets/16414613/18748819/f18126c8-80cb-11e6-83f4-dc7cc7170c0b.gif)

**Comment by timayhelen** [comment]
For the time being you can tell them that ctrl+y or cmd+shift+z is "Redo." You can always redo something is you didn't mean to undo it.

**Comment by SlavaET** [comment]
It's a common behaviour for the textareas and tinyMCE editors. Undo points are not created for every single letter, Undo points created on line breaks and some other key changes to the text. You can see exactly the same behaviour in default tinyMCE editor in the WordPress.
That said - it's not a conflict with Visual Builder's Undo/Redo mechanism, but expected behaviour for this element.
We can create custom Undo/Redo mechanism for the inline editor and store the changes on every letter, but I'm not sure whether we need this, since it'll make it work differently then anywhere else.
@timayhelen what do you think? Do we need to implement the custom undo/redo mechanism for our inline editor and store the states for every single letter? We'll still need to limit the history to some records ( like 200 ) and it'll probably create more issues if user will type a lot of text and will decide to undo some changes.

**Comment by timayhelen** [comment]
@SlavaET Let's not worry about it for now.
