### ISSUE TITLE
Fullwidth Menu :: Active link color setting doesn't working

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#539]
### Problem:

It seems the "Active Link Color" setting doesn't working.

### Steps To Reproduce:
1. Add the Fullwidth Menu module to the page
2. Assign custom Active Link Color setting
3. The color doesn't applied.

**Comment by SlavaET** [comment]
Turned out there were 2 issues:
1) "Active Link Color" option was applied to the wrong selector. This issue is not related to Divi 3 and it was a general issue with the FW menu module.
2) Active menu item was not determined correctly when VB is activated. This issue related to Divi 3.

I fixed them both in my PR.
