### ISSUE TITLE
Problem with anchor links that include some parameters

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#542]
### Problem:

For ex. if you add a pricing table module and define the following URL to the Button URL option:
```
#anfragen?form=Einzelpaket
```
this won't work. But if you add it w/o any parametters, like _#anfragen_ it will work.

I'm not sure if it's a bug. Could someone explain what actually happens? :)

Ticket:
https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=597448

**Comment by fikrirasyid** [comment]
@kary4 it isn't bug, he configure it incorrectly. If you'd like to use parameters and anchor on the URL, instead of this:

> http://domain.com#anfragen?form=Einzelpaket

OR

> #anfragen?form=Einzelpaket

You have to put the parameter first, then the anchor:

> http://domain.com?form=Einzelpaket#anfragen

OR

> ?form=Einzelpaket#anfragen

This Mozilla Developer Network explains it clearly: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL

In case you need a visual guidance, this is the incorrect URL structure:

![542-incorrect](https://cloud.githubusercontent.com/assets/916442/18867468/8bb552c2-84ce-11e6-91f9-189b19e2eeb5.gif)

This is the correct one:

![542-correct](https://cloud.githubusercontent.com/assets/916442/18867491/a1c0b174-84ce-11e6-9f73-ee8be58ca751.gif)

**Comment by kary4** [comment]
@fikrirasyid Uhh, so detailed! Thank you! /x10  👍
