### ISSUE TITLE
FB :: Text Editor :: Shortcode buttons are not visible 

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#557]
### Problem:

There are some missing buttons (shortcode buttons ) under text module (probably for any text editor under FB). 
![58500344-80d9-11e6-869b-b4f07561d614](https://cloud.githubusercontent.com/assets/3352130/18925719/b4bf16d6-85bd-11e6-8628-c64ad9c16bea.png)

**Comment by SlavaET** [comment]
Looks like we cannot simply take the custom tinyMCE plugins from WordPress and move them into our editor because of:

1. They registered only for admin pages. For example our default shortcodes registered this way:
 ```
add_action('admin_init', 'et_init_shortcodes');
function et_init_shortcodes(){
	if ( current_user_can( 'edit_posts' ) && current_user_can( 'edit_pages' ) ) {
		if ( in_array(basename($_SERVER['PHP_SELF']), array('post-new.php', 'page-new.php', 'post.php', 'page.php') ) ) {
			add_filter('mce_buttons', 'et_filter_mce_button');
			add_filter('mce_external_plugins', 'et_filter_mce_plugin');
			add_action('admin_head','et_add_simple_buttons');
			add_action('edit_form_advanced', 'et_advanced_buttons');
			add_action('edit_page_form', 'et_advanced_buttons');
		}
	}
}
```
So, they're loaded only on `post-new.php`, `page-new.php`, `post.php`, `page.php` pages.
We're using a little different hooks in Monarch and Bloom plugin, but they also loaded only on these pages. 3rd party plugins may use different admin hooks as well.

2. These custom plugins created with assumption that they're loaded on admin pages and rely on some scripts which also loaded on admin pages. Therefore even if we load these plugins in VB somehow, then we need to load all the dependancies as well and adjust the code of the plugins to make it work from VB.

I think the most acceptable solution for this issue is to add some hooks into Visual Builder similar to WordPress to allow registering of 3rd party plugins for tinyMCE in the VB. When we implement this mechanism 3rd party plugins can be added to tinyMCE, but because of issue No 2 from above they should be adjusted ( or rewritten completely ) to work in VB.

I think this change better suits the upcoming 3.1 release where we'll be thinking of extendability of Divi application.
@timayhelen what do you think?

/cc: @Jronk @uportnykh

**Comment by timayhelen** [comment]
I am going to close this for now and we can think about it again in 3.1.
