### ISSUE TITLE
Added BB (save, publish, history, portability) & FB (zoom, exit, help, cut, copy, & paste module) Shortcuts

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#578]
Faux ticket to keep track of PRs which fixes https://github.com/elegantthemes/Divi-Beta/issues/449.

See https://github.com/elegantthemes/submodule-builder/pull/1259 for the details.

**Comment by lots0logs** [comment]
@fikrirasyid 

When using the history shortcut in the BB...

![2016-10-05 16-58](https://cloud.githubusercontent.com/assets/4675662/19133274/0e9c3c1a-8b1d-11e6-80c9-81c07fe7165e.gif)

**Comment by lots0logs** [comment]
Is the save as draft shortcut <kbd>Super</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>? On Chrome nothing happens when I try it. In Firefox the Page Settings Modal opens.

**Comment by timayhelen** [comment]
@lots0logs Might be a weird linux thing. Never seen that before.

**Comment by lots0logs** [comment]
After further testing I discovered that chrome and firefox are identifying my super key differently and it makes the shortcut not work. Its weird.. check out the keydown events for my super key:

### Chrome
![2016-10- 5_05-44-22-pm](https://cloud.githubusercontent.com/assets/4675662/19134473/d7c50396-8b23-11e6-9206-52a1e3c04ea5.png)

### Firefox
![2016-10- 5_05-46-42-pm](https://cloud.githubusercontent.com/assets/4675662/19134476/dae4d5ba-8b23-11e6-8559-bf3efa3d5a81.png)

@timayhelen Linux isnt the wild west anymore..I rarely have any weird problems these days. Its been at least a few years since I had any issues :stuck_out_tongue_winking_eye:

**Comment by lots0logs** [comment]
Also should mention I use my super key for keyboard shortcuts in zendesk and intercom everyday. Never any issues :confused:

**Comment by lots0logs** [comment]
This appears to be true today as its the behavior I am seeing with Firefox:
>At least as of Firefox 48, the (⊞ Windows) key is not considered the "Meta" key. KeyboardEvent.metaKey is false when the (⊞ Windows is pressed.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by fikrirasyid** [comment]
@lots0logs ah, OSes and their differences in handling modifier key :facepalm: what distro do you use? If they handle modifier key differently, we might need to ditch the event's modifier event and use the one I just recently added for detecting multiple keys combo.

Since this issue has been closed, can you open new issue and assign it to me?

**Comment by fikrirasyid** [comment]
meanwhile I'll figure out a way to spin up actual linux and windows (got one actual windows machine for gaming but my son punch it and it keeps looping in the booting process :facepalm:) machines for testing.
