### ISSUE TITLE
Copy & Pasting Too Quickly

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#593]
@fikrirasyid If you copy and pasting a module using keyboard shortcuts twice very quickly into an empty column, it will break the layout. 

Copy a module and then mouse over an empty column. Press Ctrl + V + V + V + V quickly and watch the column structure become corrupted.

**Comment by lots0logs** [comment]
@fikrirasyid This LGTM. Though I did notice something that perhaps we can improve in this PR. When a column is empty, only a small portion at the top of the column allows pasting to be performed. This is obviously because an empty column technically has no height. Is there anything we can do to improve it? 

![2016-10-11_11-23-44](https://cloud.githubusercontent.com/assets/4675662/19279144/c24638f6-8fa5-11e6-9d41-6cd1310c58a5.png)

**Comment by fikrirasyid** [comment]
@lots0logs I've incorporated your feedback and push it to `593-fix-copy-paste-too-quickly`. Basically, empty column now has minimum height of the tallest column to make it easier to hover / copy / paste:

![hover area](https://cloud.githubusercontent.com/assets/916442/19308365/557771e0-90a9-11e6-9915-ee54f71d7936.jpg)

This is how it looks like if the column has background color:

![empty column s minimum height](https://cloud.githubusercontent.com/assets/916442/19308374/67f3fa28-90a9-11e6-9f5a-e51b0868945b.gif)
