### ISSUE TITLE
Advanced Design Settings Tab Should Display The Styles For Desktop/Tablet/Mobile Based On The Current Active View

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#594]
### Problem:
If you are viewing the page in tablet or mobile view and open a module's advanced design settings tab you see the desktop values for the options. If you change a value intending it to be for mobile view but you forget to click on the mobile icon first then it pulls you out of mobile view and into the desktop view. Its jarring to say the least. We should display the mobile or tablet values for the options based on what view is currently active. 

### Steps To Reproduce:
1.  Activate Mobile or Tablet View
2. Open Module Settings>>Advanced Design Tab
3. Modify a value without first clicking on the mobile icon.

**Comment by timayhelen** [comment]
@SlavaET I am not sure if I understand this fix correctly, but it doesn't work the way I imagined. 

Let's say you are in Tablet mode and you open up a settings modal and then you enable Responsive Editing for a setting. In this PR it will show the "Desktop" tab first, and when you make adjustments nothing happens because you are in Tablet preview. 

I think we should just keep the current preview mode and the open Responsive Editing tab synced. Right now it syncs 1 way. If you switch between the various tabs in Responsive Editing, it updates your Responsive Preview. But if you update your Responsive Preview, it does not change tabs. If we sync both ways it would fix the op issue and enhance the experience.

**Comment by lots0logs** [comment]
@timayhelen 
>Let's say you are in Tablet mode and you open up a settings modal and then you enable Responsive Editing for a setting. In this PR it will show the "Desktop" tab first, and when you make adjustment it forces you into Desktop mode. 

Hmmm..that's not the behavior I got when testing it. I will test it again.

**Comment by timayhelen** [comment]
@lots0logs Turns out I was using the wrong Divi repo. Sorry! I was tested the grunt zip task in https://github.com/elegantthemes/Divi-Beta/issues/325#issuecomment-255216437
