### ISSUE TITLE
Custom CSS For Social Media Follower Overwritten By Style.css

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#598]
Social media follow has ul appended to it in style.css

ul.et_pb_social_media_follow

Therefore these styles overwrite styles added via custom css and design settings:

```
ul.et_pb_social_media_follow {
    margin: 0 0 22px;
    padding: 0;
    list-style-type: none !important;
}
```

**Comment by lots0logs** [comment]
@SlavaET I'm not sure I understand how this addresses the issue (or perhaps I misunderstood the issue). Its my understanding that the issue is the following style in frontend-builder-style.css is too specific:
```
ul.et_pb_social_media_follow {
    margin: 0 0 22px;
    padding: 0;
    list-style-type: none !important;
}
```
Can't we simply drop the `ul` from that style in the stylesheet to resolve this? @timayhelen could you clarify the issue?

**Comment by SlavaET** [comment]
@lots0logs the problem is that selector we use in the Custom CSS options for that module are not specific enough to override the style in frontend-builder-style.css. If we drop the `ul` then some styles will not be applied properly and will be overriden by default theme styles, so I went ahead and defined more specific selector for custom css options. Also fixed a few bugs in Custom CSS processing mechanism.
