### ISSUE TITLE
Fullwidth Header (Make Fullscreen) "Stutters" on Scroll with Divi Booster

### ISSUE THREAD

**Issue by rtwintp** [elegantthemes/Divi-Beta#6]
### Problem:

My site's home page  (http://www.winerybrochures.com/) has a Fullwidth Header with Make Fullscreen set to "yes." When I have the (awesome) Divi Booster plugin active and "Hide header completely" selected, the screen "stutters" when I scroll down. In other words, it scrolls smoothly at first, then bounces before resuming.

### Steps To Reproduce:
1. Create Fullwidth Header; select Fullscreen. 
2. Activate Divi Booster plugin.
3. Select "Hide header completely" in Divi Booster's "Main Header" settings.

### Additional Information:

**Device**:
MacBook Air

**Operating System**:
OS X 10.11.3

**Browser**:
Chrome and Safari (most recent versions)

**Screen Resolution**:

**Screenshots**:
(Must scroll to reproduce…)
-

#### Before submitting your issue, please ensure the following:

- [ ] You searched this Github repo for the issue and found no open reports of the issue.
- [ ] You properly formated the issue title - eg. `Scope :: One sentence to describe the issue`.
- [ ] You have provided a detailed description of the issue.
- [ ] You have provided any/all relevant information: screenshot, screencast, page URL.
- [ ] You have provided the steps that one must take to reproduce the issue.

[View Example](https://github.com/elegantthemes/Divi-Beta/tree/master/.github/ISSUE_EXAMPLE.md)

**Comment by lots0logs** [comment]
Hi,

Generally we cannot guarantee support with 3rd party plugins as we have no control over how they are coded and there are too many plugins created to test them all. Most plugins should work, however if you are experiencing problems you will need to contact the plugin developer. I apologize for the trouble. 

If you have further questions or experience any other issues that are not directly related to the new features included in the Divi 2.7 Beta, please [open a new support ticket](https://www.elegantthemes.com/forum/posting.php?mode=post&f=187) in our forum so that we can assist you. Thanks for your cooperation :smile:

**Comment by danmossop** [comment]
Hi rtwintp, 

As Divi Booster is my plugin, I'll take over investigating this one. 

If you can let me know how best to contact you, I'll keep you updated on progress.

Thanks,
Dan

**Comment by rtwintp** [comment]
Hi Dan,

Sorry, I should have emailed you regarding the incompatibility. You may reach me at rtwintp@yahoo.com <mailto:rtwintp@yahoo.com>.

LOVE Divi Booster, BTW… Thank you for creating and maintaining such a great plugin.

Rick

**Comment by danmossop** [comment]
Thanks Rick :) 

I'll send you an email now. I think I may have a solution..
