### ISSUE TITLE
LayerSlider, Revolution Slider & Essential Grid Compatibility Issue

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#604]
We have complaints about third party shortcodes not rendering properly in the Visual Builder. The ones listed in the title of this issue are the most popular. All three plugins are available in our shared folder for testing (Shared > Plugins > Third Party). None of them work correctly, and I imagine that most third party shortcodes like these don't work. These are the only three I have tested due to the amount of complaints. 

## Layer Slider

Here is how a fullwidth slider shortcode renders in the Visual Builder:

![screen shot 2016-10-07 at 12 08 50 pm](https://cloud.githubusercontent.com/assets/3333028/19202405/e29a8ec6-8c86-11e6-8c19-918b0a4bc36f.png)

Steps to reproduce:

1. Install LayerSlider. 
2. Import the "Fullwidth Slider" demo slider.
3. Add the shortcode to the page using a Code module or Fullwidth Code module. 

## Essential Grid

Here is how the "Masonry Blog Jimmy Carter" pre-made grid renders in the Visual Builder:

![screen shot 2016-10-07 at 12 13 38 pm](https://cloud.githubusercontent.com/assets/3333028/19202536/97cf083a-8c87-11e6-8384-6901fa5833b2.png)

Steps to reproduce:

1. Install Essential Grid. 
2. Edit the settings for "Masonry Blog Jimmy Carter" and fill the grid with content. You need to select your source as "Posts" and the media type as "Featured Image" and post count to > 2. 
3. Add the shortcode to the page using a Fullwidth Code Module. 

## Slider Revolution

Here is how the slider renders in the Visual Builder:

![screen shot 2016-10-07 at 12 18 22 pm](https://cloud.githubusercontent.com/assets/3333028/19202646/42871cea-8c88-11e6-941e-6f83e1ef43f8.png)

Steps to reproduce:

1. Install Slider Revolution
2. Copy the shortcode for the demo slider that comes pre-installed. 
3. Add the shortcode to a Fullwidth Code module.

**Comment by lots0logs** [comment]
@fikrirasyid Is there anything we can do to make the container's width match what will show on the frontend page?
![2016-10-14_04-51-47-pm](https://cloud.githubusercontent.com/assets/4675662/19404182/946db3a8-9231-11e6-8260-13b5f085176d.png)

![2016-10-14_04-52-15-pm](https://cloud.githubusercontent.com/assets/4675662/19404184/98ea1d5e-9231-11e6-855d-59f72d38c8a7.png)

Still need to do some testing with revslider. Will update you with my findings asap.

**Comment by fikrirasyid** [comment]
@lots0logs how to replicate what you see above (detailed steps and import file would be really helpful)? As I've explained at https://github.com/elegantthemes/submodule-builder/pull/1311, it should've:

1. Get the width of its container
2. Render the shortcode content as wide as the width retrieved and step 1

It is actually the best guess of how wide the shortcode supposed to be. Anyway, try checking out the shortcode i variety of column (try 4_4, then 1_2 + 1_2, then 1_3 + 1_3 + 1_3). I found that some shortcode doesn't care about the width of the column and stretch the output to be 100% of the page anyway.

**Comment by fikrirasyid** [comment]
@lots0logs any update on this?

**Comment by lots0logs** [comment]
@fikrirasyid Here is the layout I used. Basically I put the grid shortcode in a regular section and in a fullwidth section. Pretty much just used the default settings for the grid. 

* [Divi Builder Layout](https://www.dropbox.com/s/uxdt2694zje3y46/essential-grid-divi.json?dl=1)
* [Ess Grid Settings](https://www.dropbox.com/s/emsey3vx324ddgh/ess_grid.json?dl=1)

**Comment by timayhelen** [comment]
@fikrirasyid I think the issue may be that some of these shortcuts "force full width." They break out of the parent content Div entirely, which means when we render the iframe inside of our row it doesn't accurately represent how the item will look at the front end. I am not sure if there is much we can do about it given how shortcodes are currently implemented.

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen I've taken a closer to the look and it appears to be fixable. The issue occurred due to iframe previewer DOM which inherits the `max-width` rule of `.container` class.  Resetting `.container` style for FB preview (determined by `$_POST` value) html fixes the issue.

The issue has been fixed at https://github.com/elegantthemes/submodule-builder/commit/d8b9223782f04d58080faad0b65677a5bf3fa42a

Here's how it looks like:

![ess-grid-on-fullwidth-section](https://cloud.githubusercontent.com/assets/916442/19475251/625e54a6-955d-11e6-96e3-7920fa13ffd9.jpg)

![ess-grid-on-regular-section](https://cloud.githubusercontent.com/assets/916442/19475250/6255adba-955d-11e6-8c53-c5dd187ef3d7.jpg)

**Comment by eduard-ungureanu** [comment]
@fikrirasyid any news about the LayerSlider?

Steps I took:
1. use the default slider that comes with the plugin
2. add a code module
3. insert the layer slider shortcode

Once I've done that the slider shows but it's very small!

<img width="960" alt="screen shot 2016-10-19 at 10 06 30 am" src="https://cloud.githubusercontent.com/assets/1719735/19508776/c1bc5a0c-95e3-11e6-8b32-10c02864cc17.png">

**Comment by timayhelen** [comment]
@eduard-ungureanu Are you using the branch attached to this issue? It has been fixed for me in this PR.

**Comment by fikrirasyid** [comment]
@eduard-ungureanu as @timayhelen have mentioned, this PR specifically fixed that issue. Have you tested this PR?

**Comment by lots0logs** [comment]
@fikrirasyid When you click inside of the shortcode container it makes the content disappear and it allows you to edit the shortcode inline. I'm not sure if this is the intended behavior? It seems buggy though. The shortcode doesn't always re-render itself properly afterwards. 

![2016-10-19 13-29](https://cloud.githubusercontent.com/assets/4675662/19532245/8946eb0c-9600-11e6-837b-5d117c10b7be.gif)

**Comment by lots0logs** [comment]
Here's what I got when testing Revolution Slider:

#### How it looks on the actual page
![screencapture-et-falgout-us-divi-revolution-slider-1476904045187](https://cloud.githubusercontent.com/assets/4675662/19533482/8ef91e62-9605-11e6-9499-8be4111ba219.png)

#### How it looks in the VB:
![screencapture-et-falgout-us-divi-revolution-slider-1476904022355](https://cloud.githubusercontent.com/assets/4675662/19533500/9f9499fe-9605-11e6-985b-5416331121b5.png)

**Comment by fikrirasyid** [comment]
@lots0logs regarding this:

> When you click inside of the shortcode container it makes the content disappear and it allows you to edit the shortcode inline. I'm not sure if this is the intended behavior? It seems buggy though. The shortcode doesn't always re-render itself properly afterwards.

That is the initial behaviour and I think it is intentional. The rendered shortcode is actually a block of text on module's `content` area which are subject of inline editor. When the cursor is being focused into inline editor's area, shouldn't everything inside the `content` are being editable?

Regarding https://github.com/elegantthemes/Divi-Beta/issues/604#issuecomment-254911199, I've mentioned the limitation of how current shortcode is being rendered in VB at https://github.com/elegantthemes/submodule-builder/issues/1311. I'll paste it here again for clarity:

> FB's shortcode rendering mechanism works similar to BB's preview mechanism:
> 
> 1. Get the shortcode
> 2. Create iFrame on the fly and pass the shortcode to iFrame
> 3. Render the shortcode on the iFrame, get the iFrame's HTML using postMessage
> 4. Print the rendered shortcode in current FB page
> 5. This mechanism is needed because some shortcode renders its content using javascript (i.e. Ninja Forms). Thus, simple PHP parsing + getting plain HTML wouldn't work.
> 
> In short, current FB's shortcode works like capturing a screenshot. It doesn't get the functional shortcode, but it at least render the visual aspect of the shortcode decently, decent enough to tell user that there is a shortcode on this module.

Also this:

> ## Notes / Known Limitation
> - This fixes the shortcode's dimension issue, but it is still not functional
> - The output of the shortcode's can be vary, as this mechanism works by capturing the UI when the iFrame is loaded. If a shortcode has particular animation and appears at 1100ms while the UI is being captured at 1000ms point, the outputted UI can be out of expectation
> 
> ## Screenshots
> 
> ![rev-slider-on-vb](https://cloud.githubusercontent.com/assets/916442/19358031/67a3159a-919e-11e6-82cb-5f6e11a59267.jpg)
> *RevSlider on VB + Issues related to animated shortcode content*
> 
> ![revslider on vb](https://cloud.githubusercontent.com/assets/916442/19358057/83948f9a-919e-11e6-8297-c10f04d6cf15.gif)
> *How RevSlider's animation works on actual front end*
> 
> ![essential-grid-on-vb](https://cloud.githubusercontent.com/assets/916442/19358076/976bbef8-919e-11e6-9ace-77fad0906e95.png)
> *Essential Grid on VB*
> 
> ![layer-slider-on-vb](https://cloud.githubusercontent.com/assets/916442/19358077/9875431e-919e-11e6-9540-4682a7e01c7c.png)
> *Layer Slider on VB*

For the time being, this is the closest one fix fits for all that I can found (another alternative for this is to make the rendering timeout significantly longer). Other attempt to make the shortcode functional are case-by-case fix. Plugin author must intentionally modify their plugin to make it compatible with VB. It's one of these:

1. We make some sort of standard for hooking into VB, and ask plugin to hook properly
2. We add specific support for specific popular plugin, such as YOAST support then include it on Divi or release it as extension.

**Comment by lots0logs** [comment]
@fikrirasyid Right I understand. What I was eluding to in my last comment was that I think it would be better to disable the inline editor for the module if its displaying a shortcode. Considering the limitations and issues we know exist with rendering the shortcodes, I think that we should try to minimize the frequency of rendering attempts (since each additional render won't always produce the same result). Disabling the inline editor would help to reduce the render attempts. @timayhelen what do you think?

**Comment by fikrirasyid** [comment]
@lots0logs it can be one of the option. But consequently, disabling inline editor when a tinyMCE has a shortcode disable this as well:

![the drawback](https://cloud.githubusercontent.com/assets/916442/19545568/88f700fe-96b1-11e6-9e59-b209898f38a8.jpg)

I'm not sure about the frequency of appearance and which case that we should prioritize, but I think it is important to notice that this will be one of the outcome of limiting inline editor when tinyMCE has a rendered shortcode.

In many cases, the shortcode parsing is pretty fast and reliable tho:

![648-editing](https://cloud.githubusercontent.com/assets/916442/19545609/dc956304-96b1-11e6-8233-a2ac3864a83d.gif)

**Comment by lots0logs** [comment]
> In many cases, the shortcode parsing is pretty fast and reliable tho:

I didnt find that to be the case in my testing. It would only render the first time correctly. I'll do some more testing today and try to mimic more real-world use...

**Comment by timayhelen** [comment]
@lots0logs Let's leave it the way it is and open a different ticket at a later time if we want to change it.

**Comment by lots0logs** [comment]
@timayhelen In my testing Essential Grid and Layer Slider are improved. Revolution slider still [has issues](https://github.com/elegantthemes/Divi-Beta/issues/604#issuecomment-254911199). Do you want to leave it as is for now?
