### ISSUE TITLE
BB :: Add Missing shortcuts for the Modals in BB

### ISSUE THREAD

**Issue by SlavaET** [elegantthemes/Divi-Beta#618]
### Problem:

- [x] Switch Tabs - <kbd>Shift</kbd> + <kbd>Tab</kbd>
- [x] Preview Module - <kbd>Super</kbd> + <kbd>P</kbd>

**Comment by SlavaET** [comment]
@fikrirasyid @timayhelen What is the shortcut for the Tabs switch in the Visual Builder modals? :) I used <kbd> Tab </kbd> in BB, but I need to update it to use the same as in VB.

**Comment by timayhelen** [comment]
@SlavaET Alt + Tab

**Comment by SlavaET** [comment]
So Windows users won't have that shortcut? It's a system shortcut on Windows.

**Comment by timayhelen** [comment]
@SlavaET Maybe we can do Ctrl + Tab? This would overwrite browser functionality to switch tabs, but I think that actually makes sense so long as it only works when a modal or tooltip is open.

**Comment by fikrirasyid** [comment]
@slava @timayhelen I remember discussing this on different thread but we haven't reached any conclusion yet :\

@timayhelen ctrl + tab is used for switching tabs in chrome.

**Comment by timayhelen** [comment]
@fikrirasyid You don't think Ctrl + Tab is a good option? It's what Chrome users to switch tabs, and I think this is a good example where it's contextually relevant to overwrite browser hotkey when a modal that contains tabs is open.

**Comment by fikrirasyid** [comment]
@timayhelen I agree that it is contextually relevant and it is save to overwrite some default shortcuts. I somehow have a slight doubt because switching tabs is kinda different tho. Some people open tabs until they only see the favicon and for these kind of user (people who do this are usually power user), switching tabs would be critical.

However, I think my initial thought was incorrect. While I write this and reading your reply, I re-checked the list of chrome (and firefox) shortcuts in windows. Jump to the next tab actually can be done by two shortcuts:

- <kbd>ctrl</kbd> + <kbd>tab</kbd>
- <kbd>ctrl</kbd>+ <kbd>pgDown</kbd>

Thus, you're right. I think <kbd>ctrl</kbd> + <kbd>tab</kbd> would be a good option

## Note
I personally rarely use <kbd>ctrl</kbd> + <kbd>tab</kbd> because IMO pressing <kbd>ctrl</kbd> in Mac feels weird. I prefer <kbd>cmd</kbd> + <kbd>shift</kbd> + <kbd>[ or ]</kbd> or <kbd>cmd</kbd> + <kbd>1 - 9</kbd>.

**Comment by timayhelen** [comment]
Yeah I use Ctrl + Tab for switching tabs, but I think if we can limit it to when a modal is open it would be perfect.

**Comment by fikrirasyid** [comment]
@timayhelen yeah, limit the shortcut to work only when the modal is opened would make it more relevant.

**Comment by SlavaET** [comment]
@timayhelen @fikrirasyid Looks like Chrome doesn't allow to catch and override the <kbd> Ctrl </kbd> + <kbd> Tab </kbd> shortcut. It partially works in Firefox, but it still switches the browser tabs, so we cannot use this combination.

**Comment by fikrirasyid** [comment]
@SlavaET I tested it out on the branch I'm working on, and I too can't override <kbd>ctrl</kbd> + <kbd>tab</kbd>. However, if you press <kbd>tab</kbd> first before <kbd>ctrl</kbd>, it can be overriden.

My suggestion for different tab shortcuts:
- <kbd>ctrl</kbd> + <kbd>tab</kbd>
- <kbd>ctrl</kbd>+ <kbd>pgDown</kbd>

**Comment by SlavaET** [comment]
@fikrirasyid but when we press Tab it'll perform default tab action first ( switch to the next field ), so <kbd>Tab</kbd> + <kbd>key</kbd> is a bit weird combination.
As for the <kbd> fn </kbd> button it doesn't exist on most Windows keyboards, it usually exists only on small Laptop keyboards and I'm not sure it works the same way as on Mac.
Probably we can use something like <kbd> Alt </kbd> + <kbd> T </kbd>, this one seems to be free and quite logical T - Tab.

**Comment by lots0logs** [comment]
This was probably already explained somewhere (sorry :grimacing: ) but why can't we use just <kbd>tab</kbd> for switching tabs (in the BB and VB)? ..actually nevermind, it literally just dawned on me that using only <kbd>tab</kbd> would cause accessibility problems (for people using screen readers) :doh:

**Comment by fikrirasyid** [comment]
@SlavaET yeah, I agree that <kbd>tab</tab> first then <kbd>ctrl</kbd> feels weird.

Using <kbd>t</kbd> key would be problematic, since we use single <kbd>t</kbd> for toggle page options. It'll unwantedly open the page options 🤔

**Comment by SlavaET** [comment]
@timayhelen so what's your decision on this?

**Comment by timayhelen** [comment]
I think it's important to use Tab and not T. Tab is was people expect for switching tabs. 

So propose that we change it from Alt + Tab to Shift + Tab. Then we need to change the Modal Snap toggle to something else. Since we currenly use Super + Enter to go full screen, maybe we change do Super + Left and Super + Right to toggle between modal snap left/right.

**Comment by SlavaET** [comment]
Done.
- Added shortcuts into BB.
- Replaced the <kbd> Alt </kbd> + <kbd> Tab </kbd> with <kbd> Shift </kbd> + <kbd> Tab </kbd> to switch the modal tabs in Visual Builder
- Replaced the <kbd> Shift </kbd> + <kbd> Tab </kbd> with <kbd> Super </kbd> + <kbd> Left </kbd> / <kbd> Right </kbd> to toggle snap location in Visual Builder
