### ISSUE TITLE
Issues with dragging duplicated fullwidth modules

### ISSUE THREAD

**Issue by timayhelen** [elegantthemes/Divi-Beta#662]
Try this:
1. Load the Homepage Basic layout. 
2. Duplicate the fullwidth section 
3. Try to drag the fullwidth header module inside the duplicated fullwidth section. It doesn't work correctly. When you try to drag the module, the entire section is moved. 

I also ran into strange issues while moving the fullwidth header module between two fullwidth sections. At some point, things start to disappear. 

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1512

**Comment by fikrirasyid** [comment]
I think I've found the cause of this issue but I haven't found a decent solution for it. If my hypothesis is correct, this issue happens because duplicated section hasn't got proper sortable setup. Section content sortable is set when component is mounted (created). We are under impression that duplicated section is newly created and mounted thus it should get proper `makeSortable()`. Meanwhile, what actually happens are, assume you have three sections:

- regular_section
- fullwidth_section
- specialty_section

If you duplicate the second section, it becomes like this:

- regular_section
- fullwidth_section
- fullwidth_section --> actually updated from specialty_section to fullwidth_section
- specialty_section --> actually newly created

Thus, if you try remove all sections below the fullwidth_section, save it, refresh the page and duplicate then try to move the section, it'll work because this time the duplicated section is actually created, not updated.

I'll continue looking for a decent solution on monday.
