### ISSUE TITLE
Empty rows with padding looks different on the front-end

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#667]
### Problem:

It's what Divider modules are for, but if a user used an empty row with custom padding to add extra space they will see different results when exiting the VB.

https://www.youtube.com/watch?v=a_aZzMvdcts

**Comment by fikrirasyid** [comment]
@FaycalBoutam on empty padding, we have to make a space for add column button. It is basically the same with empty column:

![not identical](https://cloud.githubusercontent.com/assets/916442/19619267/460747bc-988d-11e6-9ff9-92c485a33074.jpg)

If user needs a spacing, as you have said, that's why divider module are for :)

**Comment by FaycalBoutam** [comment]
@fikrirasyid I see. Thanks 👍
