### ISSUE TITLE
Visual Builder :: Map Module 

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#686]
### Problem:

Though it is not affecting on the working of the module but in Visual builder the API key is not visible in the module settings like it is shown  in backend builder
this is how it comes in backend builder
![bb](https://cloud.githubusercontent.com/assets/13402626/19828939/77414896-9df1-11e6-8606-cdc5383e6daf.PNG)
while this is how it comes in Visual Builder
![vb](https://cloud.githubusercontent.com/assets/13402626/19828942/821bfd38-9df1-11e6-81e7-7800b90f7f0e.PNG)

### Attached PR
elegantthemes/submodule-builder#1566

**Comment by lceberg** [comment]
The issue occured because, while the API Key is properly retrieved and stored to a variable, that variable is not used anywhere else.

To fix this the `this.props.value` is now stored into a variable and the API Key, when present, is assigned to that variable which is passed to the rendered input afterwards.

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1566
