### ISSUE TITLE
VB :: Countdown Timer :: Numbers Line Height

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#694]
### Problem:

The Numbers Line Height setting causing colon symbols to stays not in one line with numbers.
The Label Line Height setting do the same.
Also I've noticed the default value of this option is 64px for some reason.

The issue exists in Divi Builder as well.
![image](https://cloud.githubusercontent.com/assets/20072036/19839724/1f3341ba-9ef8-11e6-8c80-cde0d4dade6a.png)
### Steps To Reproduce:
1. Create a Countdown Timer module
2. Adjust Numbers Line Height setting

**Comment by lots0logs** [comment]
@fikrirasyid There are still issues with pretty much all options related to the countdown numbers: 

![2016-11-16 12-23](https://cloud.githubusercontent.com/assets/4675662/20360021/d4b0dbfe-abf7-11e6-8d73-2513d481567d.gif)

Honestly, I'm wondering if having these options for the numbers makes much sense. Beyond controlling the font size, there is not much benefit you get from adjusting the other options. I think we should consider removing the `line-height` option form the numbers and the label since the only thing it accomplishes is breaking the alignment. As for the letter spacing we should set a maximum value to prevent the craziness that occurs with values larger than what can fit in the container. @timayhelen what do you think?

**Comment by fikrirasyid** [comment]
@lots0logs can you elaborate what do you mean by `there are still issues`? The option now exactly modifies what it is promised (label line height modifies label line height *only*, and so on and so forth). Whether the layout breaks when excessive number is used, isn't it happen to all options in all modules?

>  As for the letter spacing we should set a maximum value to prevent the craziness that occurs with values larger than what can fit in the container

I don't think that this will work. Several weeks ago we intentionally modified the way range slider works so it works like this now:

1. Let's say we have 1 - 3 em range for slider input
2. User adds 5em to the input text
3. Now the slider has 1 - 5 em range

This is added to accommodate all kind value that user might want to use.
