### ISSUE TITLE
Visual Builder :: FullWidth Slider :: Slide Disappears After Modifying

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#696]
### Problem:

Can anyone check the following website please http://darknife.com
The slide disappears in the fullwidth slider after you add some changes under Slide Module Settings (Visual builder).
To reproduce:
1. Add fullwidth slider with one slide (Back End Builder);
2. Save and preview the page. Click Enable Visual Builder.
3. Change Background Image Size option to anything else.
4. Save the page and update. You'll see the slide does not appear anymore.

Screen-cast:
http://darknife.com/Recording3.mp4

I cannot reproduce the issue locally. 
All plugins are disabled. 
I installed a fresh divi theme.

Ask me for a token if you need,
Thanks.

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=609917

**Comment by lots0logs** [comment]
@kary4 Could you send me the token? Thanks!

**Comment by kary4** [comment]
@lots0logs Sure, here you go:

lQeMH8LbTKV%PZJ+(

**Comment by kary4** [comment]
@lots0logs I think we get more customers with this problem. One more issue here:

https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=611726

**Comment by timayhelen** [comment]
This mimics an old bug that was causing the slider module to break when it contained empty body content and the Visual Mode was enabled for TinyMCE.

**Comment by timayhelen** [comment]
Yes this is an old bug that has come back. It's something that @Jronk fixed a while ago, but perhaps the fix was not applied to Fullwidth Sliders? You can re-create the issue by doing this:

1. Open the BB. 
2. Make sure the "Visual" tab of TinyMCE is currently active. 
3. Add a fullwidth slider and a slide that has no content in TinyMCE. 
4. Save the page. 
5. Load the page in the Visual Builder.
6. Open fullwidth slider settings. 
7. Open up the child slide settings. 
8. Click the green arrow. 

![bug](https://cloud.githubusercontent.com/assets/3333028/19912518/55f304c2-a058-11e6-8b5c-07ded6a26b81.gif)

It seems to be isolated to sliders that were added and saved in the BB first. If you start with the VB using the same steps, the error does not occur.

**Comment by Jronk** [comment]
ref https://github.com/elegantthemes/submodule-builder/pull/1291
