### ISSUE TITLE
Comments Module :: Design : Button icon not working

### ISSUE THREAD

**Issue by VladET** [elegantthemes/Divi-Beta#702]
### Problem:
<img width="509" alt="capture" src="https://cloud.githubusercontent.com/assets/1061516/19858488/5658caf6-9f8a-11e6-9c5f-ca48c1cfc042.PNG">

<img width="152" alt="capture" src="https://cloud.githubusercontent.com/assets/1061516/19858455/2385f61c-9f8a-11e6-8935-6c6c6f92655a.PNG">

**Comment by lots0logs** [comment]
@fikrirasyid Please see review on PR. thanks!

**Comment by fikrirasyid** [comment]
@lots0logs I've replied and updated the branch based on your review 👍

**Comment by timayhelen** [comment]
The default button color is now incorrect in this branch. It should be blue:

![screen shot 2016-11-21 at 3 36 48 pm](https://cloud.githubusercontent.com/assets/3333028/20505242/71d74e66-b000-11e6-8103-90c10944a60e.png)

**Comment by fikrirasyid** [comment]
@timayhelen I've checked how comment module's default color works and it turns out that button form's submit button default color is determined by theme. For comparison, this is how submit button of comment module appears on Extra:

<img width="501" alt="screen shot 2016-11-22 at 1 18 13 pm" src="https://cloud.githubusercontent.com/assets/916442/20513044/2905a1a4-b0b6-11e6-92f5-d8c49cf3b9b0.png">

Thus, the patch for this PR is located at `Divi` and `submodule-builder`:

- `Divi` - branch:`702-comments-module-design-button-icon-not-working`. See: https://github.com/elegantthemes/Divi/pull/2633
- `submodule-builder` - branch: `702-comments-module-design-button-icon-not-working`. See: https://github.com/elegantthemes/submodule-builder/pull/1443

This is how it looks now:

![default comment module submit button](https://cloud.githubusercontent.com/assets/916442/20513368/024727d4-b0b8-11e6-9817-b5bf56fa6360.gif)
