### ISSUE TITLE
VB :: Builder doesn't load with Scandinavian characters inside content

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#712]
### Problem:

![image](https://cloud.githubusercontent.com/assets/20072036/19889639/02af68de-a047-11e6-9990-51c2a355d932.png)
Originally the issue comes from this ticket -> https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=599038
I can't reproduce the issue on my end.
Therefore I've created the test page -> http://designcraft.se/demo/test-page-by-et-support/
Here the support token: 7arj+gHxEdVLk1A6-  (expires 4 nov)
Login URL is http://designcraft.se/demo/wp-admin

**Comment by SlavaET** [comment]
Was able to debug this issue on customer's website, it takes me some time though.
It happens because `html_entity_decode()` function returns `null` when try to encode the Scandinavian characters because of old PHP version. It's php 5.3 on customer's website and this error doesn't exist in the later php versions.
Anyway I implemented a fix, so it will work fine with php 5.3 as well.
