### ISSUE TITLE
VB :: Slider Module :: Some settings hints are not working

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#715]
@dm-chechik commented on [Tue Nov 01 2016](https://github.com/elegantthemes/divi-builder/issues/701)

### Problem:
 
I've noticed the **Background Image Position** and **Background Image Position** hints are not working. There is no happens after click on "?" symbol.

---

@lots0logs commented on [Tue Nov 01 2016](https://github.com/elegantthemes/divi-builder/issues/701#issuecomment-257708001)

@dm-chechik With which theme does this occur? 

---

@dm-chechik commented on [Tue Nov 01 2016](https://github.com/elegantthemes/divi-builder/issues/701#issuecomment-257711094)

@lots0logs It seems I had to create the issue under the Divi-Beta, sorry.

**Comment by SlavaET** [comment]
@lots0logs we don't have a description for these fields, so nothing happens when you click on the `?` 
I improved the appearance of `?` icon in scope of this issue - https://github.com/elegantthemes/Divi-Beta/issues/779
So if the field don't have a description, then `?` icon won't appear.

@lots0logs do we need to add the description for these fields? Probably we have some more fields without description in different modules, so we need to review and list all the options where we want to add it.

**Comment by lots0logs** [comment]
@SlavaET 
>do we need to add the description for these fields? Probably we have some more fields without description in different modules, so we need to review and list all the options where we want to add it.

Yes, but I think we can wait and do it in 3.1.
