### ISSUE TITLE
RTL :: Columns stacking order

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#743]
### Problem:

Right now on RTL sites at mobile layout columns are stacked from left to right.
![image](https://cloud.githubusercontent.com/assets/20072036/20177130/3ba209e6-a75c-11e6-96ab-629e122e8767.png)
![image](https://cloud.githubusercontent.com/assets/20072036/20177140/418f638a-a75c-11e6-93b3-1283303cfc2d.png)

Can we do something to change stacking order to right to left?

**Comment by lots0logs** [comment]
@fikrirasyid Currently, users with RTL sites are using the existing column order as if its RTL even though its technically not. What I mean is that even though the the theme currently expects and accounts for the column content to be 1|2|3|4, users with existing RTL sites actually have 4|3|2|1. This PR fixes the problem for any newly created content but I think it has the opposite affect on existing content. Floating the columns to the right will reverse the order which, for existing content, would not be desired. Please do correct me if I am wrong because this is not the easiest concept to grasp :grimacing:

**Comment by fikrirasyid** [comment]
@lots0logs what you're describing is correct. this is how current RTL column looks like. Remember, read it from right to left. You'll find the order is: 3 -> 2 -> 1:

![743-1](https://cloud.githubusercontent.com/assets/916442/20780679/70c732d2-b7af-11e6-8da0-a77c8c4b1a43.jpg)

This is confusing once the layout enters mobile screen, because the order is still left to right which is 1 -> 2 -> 3:

![screen shot 2016-12-01 at 10 18 56 am](https://cloud.githubusercontent.com/assets/916442/20780698/999b9d7e-b7af-11e6-9ba8-4681ee0e6acb.png)

https://github.com/elegantthemes/Divi/pull/2636 and https://github.com/elegantthemes/submodule-builder/pull/1468 enables user to use "right to left column ordering". This is how the layout above works with this option turns on:

![743-2](https://cloud.githubusercontent.com/assets/916442/20780726/df4ccd84-b7af-11e6-8654-ba57c0c1e765.jpg)

This column ordering is consistent with how it looks on mobile:

![743-3](https://cloud.githubusercontent.com/assets/916442/20780738/fd188380-b7af-11e6-8537-986b3c119c36.jpg)

***

> Floating the columns to the right will reverse the order which, for existing content, would not be desired.

**Exactly**. That is why this option is turned off by default and user needs to turn it on manually: to avoid unwanted issue with existing content.

***

> So..assuming I'm correct in what I've just explained, we should probably add a note explaining this in the help modal for the option (will include copy below just in case)

We already have description of this option. Do you think we need to explain it more?

![screen shot 2016-12-01 at 10 14 33 am](https://cloud.githubusercontent.com/assets/916442/20780766/373c5e74-b7b0-11e6-9378-ee6c5ae8712b.png)

However, there are some caveats:

1. The option hasn't been translated yet
2. This option only appears if the site's language setting is set to RTL language. 
3. ePanel apparently has a bug in RTL layout (incorrect help icon position, incorrect close modal position):

![743-epanel](https://cloud.githubusercontent.com/assets/916442/20780781/5ec6d6d6-b7b0-11e6-9feb-5c97d076ef8d.gif)

I'll open different ticket to specifically fixes this ePanel in RTL issue.

***

> I think we should move the epanel option into the Layout>>General tab.

I've moved the option to `Layout > General Settings` tab via https://github.com/elegantthemes/Divi/commit/45397d34b2991d060604b9a737dfa0a9b229e0ee

![743-4](https://cloud.githubusercontent.com/assets/916442/20780905/84736a4c-b7b1-11e6-9ff0-07834f2922fc.jpg)

**Comment by fikrirasyid** [comment]
@lots0logs this is the ticket for related ePanel issues: https://github.com/elegantthemes/Divi-Beta/issues/818

**Comment by lots0logs** [comment]
@fikrirasyid Please see my review comment on the PR. One other thing. I think it makes sense for this option to be enabled by default on fresh installs of the theme or builder. Can that be easily achieved without going too far beyond the scope of this PR.?

**Comment by fikrirasyid** [comment]
@lots0logs I've replied and push changes to incorporate your feedback.

> I think it makes sense for this option to be enabled by default on fresh installs of the theme or builder (which use RTL language of course)

I agree that it feels logical, but I think this would be really prone to error tho. Several "point" where we can detect whether the site is "fresh-installing" Divi or has been around:

- Using `et_theme_epanel_reminder()`. However this can get re-triggered again and again if somehow user removes the theme options row.
- Added during theme activation and is_rtl() detection. However this could go incorrectly if user switching between themes.

Given the flaws, I think it is still better to have user manually update the option via theme option.

**Comment by lots0logs** [comment]
@fikrirasyid Could we check the database for posts that have the `et_builder_enabled` key set? So basically if we detect no existing builder posts and RTL language is used we enable the option automatically.

**Comment by fikrirasyid** [comment]
@lots0logs that is a good idea! So if:

1. Builder is never been used (no post / page with Divi builder meta)
2. is RTL

Automatically set the RTL column ordering. Is that what you mean?

***

Anyway, I just think of this: let's say we implement automatic RTL column ordering for new site and it works as expected. How we'll handle existing user's question: "Why it doesn't automatically turned on on my site? How to turn it on?". Basically I think we need to communicate to existing RTL user that we have this option to properly set the RTL column ordering and since you already have content, you need to manually activate it. What do you think?

**Comment by lots0logs** [comment]
@fikrirasyid 

> Is that what you mean?

Yes, exactly :smiley: 

>What do you think?

I agree. So basically, this is what we need to do:

* Upon theme activation, enable the RTL option automatically if all of the following conditions are met:
  1. The site is using an RTL language.
  2. We've never automatically enabled the RTL option before.
  3. There are no existing builder posts.

If the first two conditions are met but the 3rd one is not, then we should set a flag that RTL notice should be shown to the user in the builder once.

* Upon loading the builder, check to see if flag is set and if so, display the following notice once:
  * Modal Title: Divi Builder Notice
  * Modal Body: The Divi Builder has been updated with improvements to the responsive layout of it's columns for RTL websites. Unfortunately, these improvements are not backwards compatible, so they have not been enabled by default. You can enable the improvements in {Divi's|the Divi Builder Plugin's} options panel under the <strong>Layout</strong> tab.

**Comment by fikrirasyid** [comment]
@lots0logs can you take a look at the branch again? Please note that, there are four branches involved with this update:

- `/Divi`: `743-rtl-columns-stacking-order` branch
- `/submodule-builder`: `743-rtl-columns-stacking-order` branch
- `/submodule-core`: `743-rtl-columns-stacking-order` branch
- `/submodule-epanel`: `743-rtl-columns-stacking-order` branch

I basically agree and have implemented all the point you suggested above except for the notice form. However Instead of pop up modal, after observing it, I went with this kind of admin notice bar which we already use:

![screen shot 2016-12-03 at 6 03 08 pm](https://cloud.githubusercontent.com/assets/916442/20858937/c6e7c058-b982-11e6-9ea4-9bd7c63db00b.png)

Several reason that brought me to my conclusion that it is better to use notice bar instead of modal

1. Modal is obtrusive. It blocks user from doing anything before the modal is closed. 
2. We might have multiple notices. In fact, we already have it now by doing RTL column notice. This is a totally possible scenario if the site is RTL, uses Extra, already has builder powered post / pages, then switch to Divi after this update is pushed. If we're using modal, we'll either have modal with long description or multiple modals (which are really obtrusive). On the other hand, notice bar will simply look like this:

![notice bar ftw](https://cloud.githubusercontent.com/assets/916442/20858976/36a2e20a-b984-11e6-98aa-28209cf792eb.jpg)

In anticipation of no. 2, I can imagine that in the future we'll have "new feature activation sequence" which requires us automatically update an option if certain conditions are met. Thus, I put some time to figure out a solid API for this (I referenced it as `Activation + Admin Notice Mechanism` on various commit message). Please take a look at the following commits:

- `submodule-builder`: https://github.com/elegantthemes/submodule-builder/commit/7790d6da2b84934711f2891a799a8193ab55d74e
- `Divi`: https://github.com/elegantthemes/Divi/commit/44051eebcc98e99ec90adda953e55dc699a64a01

To further test the mechanism, I replaced this existing new site notice:

![screen shot 2016-12-03 at 6 03 08 pm](https://cloud.githubusercontent.com/assets/916442/20858937/c6e7c058-b982-11e6-9ea4-9bd7c63db00b.png)

Using the new activation + admin notice mechanism. I think this will significantly simplify the process of adding activation and displaying admin notice. 

## Note
- Since this includes introducing "API" for doing particular task, I think @uportnykh, @Jronk, @Anny85, @SlavaET might want to review and giving sharing their opinion / concerns as well. I tagged them to let them know.

**Comment by lots0logs** [comment]
@fikrirasyid @timayhelen @Jronk @SlavaET I think the admin notice handling that's included in this PR would serve us much better as a core component. It would require a bit more effort to properly abstract it so that its useful as a core component but I think it'll be worth it in the long run. Thoughts?

**Comment by dm-chechik** [comment]
Hi! Any estimate when we will release this feature?
