### ISSUE TITLE
Divi Library :: Global Item :: Changes in global item do not reflected to the item copy

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#773]
### Problem:

If I have two or more copies of the same global element on a page any changes in global items do not reflected to the copies immediately. I can see the changes only after reloading Visual Builder.
![screen](https://cloud.githubusercontent.com/assets/20072036/20391140/25d42310-ace3-11e6-8405-e26b6ef145b5.gif)

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1525

**Comment by lots0logs** [comment]
@fikrirasyid It works pretty well. Though I did uncover a case where two global rows get out of sync (only until the page is refreshed). Basically if you try to move a module from one of the copies of the global row into the other copy of the global row they become out of sync visually. Refreshing the page shows them correctly again. 

![2016-12-16 15-19](https://cloud.githubusercontent.com/assets/4675662/21278970/8851596e-c3a3-11e6-857b-28fe04fe8900.gif)

**Comment by fikrirasyid** [comment]
@lots0logs are those two global sections you're testing is actually the same divi library item? If it is the case, I've successfully replicated it and I think the behaviour displayed above is actually correct. Consider this:

![divi-beta-773-step-1--3](https://cloud.githubusercontent.com/assets/916442/21287212/d94bae46-c498-11e6-8950-8f95d1b54207.jpg)

![divi-beta-773-step-2-explained](https://cloud.githubusercontent.com/assets/916442/21287222/f6cffb98-c498-11e6-9d5f-78eda49b3e87.jpg)
*Click image to enlarge the picture*

Bottomline, I don't think it is a bug. It is basically a logical consequence of moving global item's children to another global item which shares the same ID. It is possible; but if you do it, it'll be weird.

The only adjustment that is logical to do is to prevent global item to move its child to another global item which has the same ID (identical global item). However I personally think leaving it as it is are better option.

**Comment by lots0logs** [comment]
@fikrirasyid Those are global rows, not sections. But yes they are the same global item as that is the topic of this github issue (right?). 

I think the modules should not change when the page is refreshed. Since this PR attempts to keep them in sync with how they will appear on the frontend I think keeping the behavior shown in my screencast makes it seem buggy from a user perspective. Could we detect this special case and do one more refresh of both rows so that they appear correctly?

**Comment by fikrirasyid** [comment]
@lots0logs before we can consider this:

>  Could we detect this special case and do one more refresh of both rows so that they appear correctly?

The question that need to be answered is:

1. The same two items are changed at the same time, the origin row and the destination row
2. Both items sent AJAX update to update itself and update all the same library item on the page
3. **Both items are changed at the same time**. Which one we need to update and which one that we shouldn't update? The origin, or the destination? Either results will feel not intuitive, IMO.

**Comment by lots0logs** [comment]
@fikrirasyid 
>Both items are changed at the same time. Which one we need to update and which one that we shouldn't update? The origin, or the destination? Either results will feel not intuitive, IMO.

Good point. Considering that, I think it makes more sense to disallow moving modules between two copies of the same global row or section.

**Comment by fikrirasyid** [comment]
@lots0logs noted. Looks like it is the most intuitive behaviour possible in this case. I'll add that restriction.

**Comment by lots0logs** [comment]
@fikrirasyid Can we make it so that we don't show drop zones for this case?

**Comment by fikrirasyid** [comment]
@lots0logs I've adjusted the drop zone behaviour.

**Comment by timayhelen** [comment]
@fikrirasyid There are issues with this branch. 

1. Save a module as global. 
2. Duplicate the module. 
3. Open the duplicated module settings. 
4. Close the modal and attempt to open the original global module settings. 

![screen shot 2016-12-29 at 11 47 41 am](https://cloud.githubusercontent.com/assets/3333028/21553407/f7132b02-cdbc-11e6-83c3-a43b8edfd2ea.png)

**Comment by fikrirasyid** [comment]
@timayhelen I've fixed this via https://github.com/elegantthemes/submodule-builder/commit/ac81829eca66bef31ee153a63f7e01d00327f6ba.

**Comment by timayhelen** [comment]
@fikrirasyid Global modules on the page no longer sync at all for me, which I know is the purpose of this ticket. Can you check?

**Comment by fikrirasyid** [comment]
@timayhelen can you provide steps for replicating the issue and its screencast? I've checked the branch and it appears that it works as intended.

This is how syncing global module performs as expected:

![773-test-module](https://cloud.githubusercontent.com/assets/916442/21790471/1a1b787e-d70f-11e6-9f2e-2789e49a20f0.gif)

This is how syncing global row performs as expected:

![773-test-row](https://cloud.githubusercontent.com/assets/916442/21790486/29ae688c-d70f-11e6-9854-ad00d81ac9ea.gif)

This is how syncing global section performs as expected:

![773-test-section](https://cloud.githubusercontent.com/assets/916442/21790498/37873556-d70f-11e6-8a6d-92499e26bd9a.gif)

**Comment by timayhelen** [comment]
@fikrirasyid I dono how I managed it, but it works now, lol. Must have been a cache issue. Sorry!

**Comment by timayhelen** [comment]
@fikrirasyid I notice a few things don't sync correctly:

- [ ] Draggable Padding doesn't sync when changed
- [ ] Inline Editor changes don't always sync (sometimes they work, but they usually fail for me)
- [ ] If you add a Blog Module to a duplicated global row, it will fail to sync correctly on the other copy of the row.

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed several commits to fix the following bugs:

> Draggable Padding doesn't sync when changed

This issue occurs because we haven't hooked library saving mechanism when padding drag edit is done.

![773-padding-drag](https://cloud.githubusercontent.com/assets/916442/21851244/c817c1a8-d840-11e6-9097-53bd641b4b25.gif)

>  If you add a Blog Module to a duplicated global row, it will fail to sync correctly on the other copy of the row.

This issue actually occurs to all module (which is children of global row/section) which uses computed attributes. 

This issue is basically:

1. Let's say we have two same global row / section on a page.
2. https://github.com/elegantthemes/submodule-builder/commit/94a974d5fe2bdd242575dfe056656044e9c4adc0 have enabled VB to sync the change made to a global section / row / module to the same global item within the same page
3. However, if module which uses computed attributes (blog, shop, portfolio, gallery, etc) is added to global row / section, its sibling (the same global row/section) will not display the newly added module (react tab on dev tool shows that the module is added to the layout tho)

This issue is caused by:

1. When syncing global element on the same page, `updateGlobalModule()` is triggered
2. `updateGlobalModule()` gets the actual global module (it can be the passed module or its parent) and being saved as `globalModule` variable.
3. `globalModule` variable is used for syncing the newly added content to the global element's sibling
4. Before `globalModule` is used to sync global element to its sibling, `shortcodeObjectSaveEssentials()` is being called.
5. Somehow, right after `shortcodeObjectSaveEssentials()` is called, `globalModule`'s attributes are trimmed into the `shortcodeObjectSaveEssentials()` version.
5. This trimmed element object has no computed attribute element which caused the failure of rendering the module's content

Thus, the most possible cause for this issue is javascript's "copy by reference" behaviour. @jronk explains this as "assigned by reference": https://elegantthemes.slack.com/archives/divi3-0/p1469059447000142

![773-padding-computed-field-module](https://cloud.githubusercontent.com/assets/916442/21851337/375a81d6-d841-11e6-80c3-d313633214fb.gif)

Syncing computed field, due to its AJAX fetching behaviour, causes a consequences. Syncing content to Divi Library is performed when settings-modal save button is closed for performance reason. Thus, if computed field ajax request hasn't been done but the settings-modal is closed, the correct returned value will never been synced to global module siblings. To avoid this issue from happening, settings-modal will not be able to be closed when computed field ajax request hasn't been done. See: https://github.com/elegantthemes/submodule-builder/commit/d1abe316a8474f2ca8e370ae992e00791926bc88

***

Regarding this issue: 

> Inline Editor changes don't always sync (sometimes they work, but they usually fail for me)

I've tried to replicate it but it works as expected. The sync is triggered when cursor leaves the inline editor either by escape or focusing other area. Can you provide a screencast / steps to replicate the issue?

**Comment by lots0logs** [comment]
@fikrirasyid Changes made with the inline editor are not syncing to the other module instance at all for me.  Steps to reproduce:

1. Use the inline editor to change a sentence in the text to be bold.
2. Click out of the inline editor. 
3. Nothing happens. 

Same is true when adding.removing text instead of just changing styles.

**Comment by timayhelen** [comment]
@fikrirasyid It seems to work title areas where in the inline editor is not fully activated, such as CTA Titles, but it does not work for the main content area. 
![global](https://cloud.githubusercontent.com/assets/3333028/21874674/5718767e-d82b-11e6-986d-8137f73a6a13.gif)

**Comment by fikrirasyid** [comment]
@timayhelen @lots0logs I've fixed the issue of syncing seems not to work on inline-editor:

![773-on-inline-editor](https://cloud.githubusercontent.com/assets/916442/22030517/6d6db2b0-dd10-11e6-9b71-258dc34d1d0e.gif)
