### ISSUE TITLE
VB :: Blurb Module :: Icon alignment

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#774]
### Problem:

It seems the blurb icon is not centered. The icon is slightly pushed to the right. Please look at the screenshot. I have marked the empty space.
The issue exists in Divi Builder as well.
![capture](https://cloud.githubusercontent.com/assets/20072036/20397148/bb7dfda8-acf9-11e6-94e0-0180f853c5ce.PNG)

### Steps To Reproduce:
1. Create Blurb Module
2. Set any Blurb icon
3. Enable Circle Icon

**Comment by fikrirasyid** [comment]
@lots0logs @timayhelen @mariomaruffi do we have a document which explained how we generate our module fonts? I've cross-checked this icon alignment issue and it appears that many icons are aligned correctly *and* incorrectly. There's no sign of CSS issue on this, so I think this is caused by the alignment in the font icon. 

This is the result of testing on 56 icons on blurb. Note: `A` means `aligned`:

![blurb icons](https://cloud.githubusercontent.com/assets/916442/20705123/5471d2ce-b654-11e6-815b-d4bf1485e562.png)

If we picked any skewed icon and check it on other module we can se that it is skewed / not aligned as well on other module:

![screen shot 2016-11-29 at 4 54 26 pm](https://cloud.githubusercontent.com/assets/916442/20705179/89712ede-b654-11e6-89b9-f0b1519950b4.png)

Thus, I think the proper way to fix this issue is to fix the alignment issue and try re-generate the font icon. I'm not 100% sure how we generate the icon tho (I remember that we're using icomoon app, but I don't know the whole workflow for it).

**Comment by fikrirasyid** [comment]
In case you're interested on testing the skewed icon, this is the layout I'm using to test the icon alignment on blurb module above: 
[774-blurb-icon-test.json.zip](https://github.com/elegantthemes/Divi-Beta/files/618633/774-blurb-icon-test.json.zip)

**Comment by timayhelen** [comment]
I don't think it's practical to fix this. It's not as simple as just increasing the icon's size because it will result in pixelated icons. We would need to re-think the whole system that Kenny designed and it wouldn't be worth the effort right now.
