### ISSUE TITLE
Certain page layout is slowing down the Firefox browser

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#777]
### Problem:

The issue comes from customer ticket -> https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=615852
Seems the issue caused by the Fullwidth Slider.
I've exported the page and successfully reproduced the same problem on my local enviro.
The page layout is included below. Tick any posts category so the Fullwidth Slider will be able to show some posts.
![image](https://cloud.githubusercontent.com/assets/20072036/20407306/cb076200-ad21-11e6-9496-169d71812531.png)

**Operating System**:
Windows 7 Pro 64-bit

**Browser**:
Firefox 50.0

**Link To Download Layout JSON File**:
https://www.dropbox.com/s/85nrg0gpki46eae/Layout%20do%20Divi%20Builder.json?dl=0

**Comment by lots0logs** [comment]
@dm-chechik I am unable to reproduce the issue. However it sounds like a bug in Firefox. Could you ask the customer to update to the latest version of Firefox and see if the issue persists? Thanks.

**Comment by dm-chechik** [comment]
@lots0logs I've checked on the latest version 50.0 
The issue appears after 2-3 minutes.

**Comment by fikrirasyid** [comment]
@dm-chechik can you ask the access token to the customer so I can access it directly? I don't think the issue can be replicated locally due to the following reason:

1. The post slider relies on post (post type) content which isn't included on the imported layout
2. The layout uses third party plugin for displaying the slide content:

![screen shot 2016-11-23 at 11 44 05 am](https://cloud.githubusercontent.com/assets/916442/20551375/2dfedab0-b172-11e6-973a-54016727ce00.png)

Based on what we have right now, I have at least two suspicion on what is actually happening:

1. User uses lots of image which is not compressed or resized for the web
2. This is might be caused by the `[post-slides categories='7']` shortcode which is placed on the code module. Can you ask user to removed the code module (and its shortcode) and see whether the issue remains?

**Comment by fikrirasyid** [comment]
Anyway, I tried accessing the URL appears on the screenshot (http://wordpress.cradim.home/) and I couldn't access it. Is it accessible for you?

**Comment by dm-chechik** [comment]
@fikrirasyid Actually it's my local test server address. Sorry :) I've asked customer to generate a new token.

**Comment by fikrirasyid** [comment]
@dm-chechik any update on this?

**Comment by fikrirasyid** [comment]
I've coordinated with @dm-chechik and no response from the customer so far. I'm closing this issue now. Feel free to reopen the issue once the customer replied.
