### ISSUE TITLE
WP 4.7 :: FB :: Inconsistent User-specific localisation on Visual Builder

### ISSUE THREAD

**Issue by fikrirasyid** [elegantthemes/Divi-Beta#799]
### Problem:

WordPress 3.7 introduces user specific language setting (site can be set to a particular language and user has different language setting that the site's language. See this post for What's coming on WP 3.7: http://www.wpbeginner.com/news/whats-coming-in-wordpress-4-7-features-and-screenshots/). When site and user has different language setting, the output on visual builder looks inconsistent. This is what happens when the following setting is used:

- Site language: Hebrew
- User language: French

Expected output: Visual builder, admin bar, etc uses French. 

Current output:
- Modal's field label are in French
- Admin bar and the rest of the page are still in Hebrew
- BB properly uses French

![screen shot 2016-11-25 at 2 09 17 pm](https://cloud.githubusercontent.com/assets/916442/20617094/62ca8fac-b319-11e6-8a07-cdbc3a16b80f.jpg)

### Steps To Reproduce:
1. Update WordPress to WP 3.7 RC 1 
2. Set Builder post on VB Hebrew
3. Set current user's language to French
4. Open any Divi Builder post on VB

### Additional Information:
**Device**:
Macbook Pro Retina 15"

**Operating System**:
OSX El Capitan

**Browser**:
Latest Chrome

**Screen Resolution**:
2560x1440 + 1440 x 900 (dual monitor)

**Comment by SlavaET** [comment]
Note: there are 2 PRs:
1) For the Divi theme - https://github.com/elegantthemes/Divi/issues/2643
2) For the Divi Builder Plugin - https://github.com/elegantthemes/divi-builder/issues/864
Both PRs add the same function into appropriate place in theme and plugin.

@timayhelen I used the code from default WP function and added a reference to that function, please take a look and let me know if it's an appropriate credit reference or not:
```
// The below code is modified version of load_translations() from /wp-includes/class-wp-locale-switcher.php
```

**Comment by lots0logs** [comment]
@SlavaET Can we do this with a single new function added to `core/functions.php`?

**Comment by SlavaET** [comment]
@lots0logs no, we can't. 
It'll work in Divi, but won't work in plugin because in Divi we init the `core` at `after_setup_theme` hook, but in plugin it's initiated at `init` hook which is too late. We need to run localization function at `after_setup_theme` hook otherwise it won't be applied.

**Comment by timayhelen** [comment]
@SlavaET WordPress's full copyright notice needs to be added, and we need to add it to CREDITS.md as well (to both Divi, Divi Builder and Extra). 

Here is an example of what was added for our WordPress tinymce adaptation:

TinyMCE Media Upload Functions sendAttachment & addMedia
--------------------------------------------------------

includes/builder/frontend-builder/bundle.js

```text
Code From WordPress

@copyright 2016 by the WordPress contributors.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

This program incorporates work covered by the following copyright and
permission notices:

b2 is (c) 2001, 2002 Michel Valdrighi - m@tidakada.com - http://tidakada.com

b2 is released under the GPL

WordPress - Web publishing software

Copyright 2003-2010 by the contributors

WordPress is released under the GPL
```

**Comment by SlavaET** [comment]
@timayhelen done.
Also submitted a PR for Extra theme which I missed initially - https://github.com/elegantthemes/Extra/issues/1509

**Comment by lots0logs** [comment]
@SlavaET I'm seeing an issue with loading the Premade Layouts modal content as well as the Portability modal content. The AJAX request is returning a 502 bad gateway error. There's nothing in the logs. It only happens with Divi (works fine for Extra and builder plugin). I thought that [this](https://github.com/elegantthemes/Divi/pull/2643#pullrequestreview-11391113) was causing the issue but the issue persists after correcting the line in that file. 

Also, I noticed that the Visual Builder butten in the admin bar is not translated in the user language. Though it appears to be a problem with WordPress since several of the core links are also not in the user language (user language was English below)

![2016-12- 5_09-28-36-am](https://cloud.githubusercontent.com/assets/4675662/20890914/56bf73aa-bace-11e6-8b3c-55f938807c15.png)

**Comment by SlavaET** [comment]
Does it work fine on master? It reminds me this issue - https://github.com/elegantthemes/Divi-Beta/issues/805

**Comment by lots0logs** [comment]
@SlavaET Looks like it doesnt work on master either. I dont think its the same as #805 b/c the response is 502 (not 500) and there isn't a OOM error showing up in the logs. Its weird. I will check to see if I can reproduce it on a different server (in case the issue is something local to my test server)

**Comment by SlavaET** [comment]
@lots0logs I fixed the issue you pointed in the comments. Please check again.
As for the Admin bar - yes, looks like WordPress doesn't have mechanism to translate the admin bar on front-end yet, so our link is not translated as well. Though it's translated when Visual Builder enabled because translation switching preformed by the text domain and we switch the translation of everything with `et_builder` domain.

**Comment by lots0logs** [comment]
@timayhelen Please check to see if the Premade Layouts and Portability modals in the VB load properly for you on this branch. I'm pretty sure the issue I am seeing is local to my server but its better to be safe than sorry!
