### ISSUE TITLE
Incorrect additional top padding value on transparent menu

### ISSUE THREAD

**Issue by dm-chechik** [elegantthemes/Divi-Beta#810]
### Problem:

~~There is unwanted additional padding appears if any transparency value is added to the main menu.
Especially it noticeable with Slide In type menu.~~ Please see my comment below: https://github.com/elegantthemes/Divi-Beta/issues/810#issuecomment-263888972

We're fixing the additional top padding adjustment on first section when primary nav background is transparent and the first section uses different custom paddingTop and paddingBottom.
 
![screen](https://cloud.githubusercontent.com/assets/20072036/20712580/bed6d186-b655-11e6-89cb-bb18b8f327a7.gif)

**Link To Download Layout JSON File**:
https://www.dropbox.com/s/z87to004ddy94a6/Divi%20Builder%20Layout%20%2812%29.json?dl=0

## Attached PRs
-  https://github.com/elegantthemes/Divi/pull/2646
- https://github.com/elegantthemes/submodule-builder/pull/1495

**Comment by fikrirasyid** [comment]
@dm-chechik @lots0logs additional `paddingTop` added to the first section **when the primary nav is set to transparent** is actually intentional. This is basically how it works:

![divi transparent primary nav background adjustment](https://cloud.githubusercontent.com/assets/916442/20756288/bb746b9e-b744-11e6-9266-75c0e278e98e.jpg)

PR where this adjustment is firstly added: https://github.com/kary4/Divi/pull/37

However, I checked the layout you attach and I notice that there is a flaw in current implementation.  Basically the additional paddingTop is incorrect if the first layout's custom paddingTop and paddingBottom is different. Thus, we'll fix it on this issue. I'll explain the details on the PR message.

Related commit: https://github.com/elegantthemes/Divi/commit/4964aca2dba4ced91b9865576c3b55eff1698c14 and https://github.com/kary4/Divi/commit/3cee8add56144d993c226400c9935c00df6

**Comment by fikrirasyid** [comment]
Patches for this issue are located at:

- `Divi`: `810-unwanted-additional-top-padding-with-transparent-menu` branch. See: https://github.com/elegantthemes/Divi/pull/2646
- `submodule-builder`: `810-unwanted-additional-top-padding-with-transparent-menu` branch. See: https://github.com/elegantthemes/submodule-builder/pull/1495

For more details about this issue, please read the PR message at https://github.com/elegantthemes/Divi/pull/2646

**Comment by lots0logs** [comment]
@fikrirasyid Could you fix merge conflicts on elegantthemes/Divi#2646? Thanks!

**Comment by fikrirasyid** [comment]
@lots0logs I've fixed the merge conflict on https://github.com/elegantthemes/Divi/pull/2646.

**Comment by timayhelen** [comment]
@fikrirasyid I tested out the branch, and added a section with a custom Padding Tp value of 10px. However the 10px value doesn't seem to take affect on the front end. 

![screen shot 2016-12-09 at 3 49 50 pm](https://cloud.githubusercontent.com/assets/3333028/21068473/26dbd226-be27-11e6-97dd-79ed5c016f3f.png)

**Comment by timayhelen** [comment]
@fikrirasyid I testing this out with a section with 10px padding top, however the padding adding to the header seems to be too much. Exactly 10px too much, curiously:

![screen shot 2016-12-09 at 3 51 37 pm](https://cloud.githubusercontent.com/assets/3333028/21068543/871b41da-be27-11e6-9ede-97bd83c34db2.png)

**Comment by fikrirasyid** [comment]
@timayhelen isn't it the correct behaviour? I've checked it and here's how it works:

![et_pb_section paddingtop explanation](https://cloud.githubusercontent.com/assets/916442/21073542/ed1c9eb0-bf13-11e6-81a8-7c0664103e93.jpg)

The layout above probably much more clearer if the row's padding is set to `0px`, being set to fullwidth, then the gutter width is set to `1`:

![et_pb_section paddingtop explanation 2](https://cloud.githubusercontent.com/assets/916442/21073552/24a8c6f6-bf14-11e6-80f7-bc50ac4ea7c4.jpg)

Isn't it the expected behaviour?

**Comment by timayhelen** [comment]
@fikrirasyid Ah you are right, sorry!

**Comment by fikrirasyid** [comment]
@timayhelen no problem (҂'̀⌣'́)9
