### ISSUE TITLE
Inline Editor :: Unwanted <br> tag when removing empty line

### ISSUE THREAD

**Issue by andrey-agp** [elegantthemes/Divi-Beta#816]
### Problem:

![animation](https://cloud.githubusercontent.com/assets/9657712/20748292/c480ea78-b717-11e6-8e63-dae7fe9629aa.gif)

### Attached PR
- https://github.com/elegantthemes/submodule-builder/issues/1504

**Comment by SlavaET** [comment]
This one was pretty difficult to fix.
The issue that tinyMCE was not adding line-breaks properly and it was displayed incorrectly inside the VB, and was buggy when you add/remove them.
I was not able to find the configuration for tinyMCE which could consistently fix this issue, so I developed a custom solution. It took me quite a long, because I tried a lot of different solutions before I found the most consistent one which works inside Inline editor and doesn't break the content for tinyMCE editors in the BB and in settings modal.
The main problem is when you hit `return` tinyMCE adds `<p><br data-mce-bogus="1"/></p>` so it adds an huge line-break, because `<p>` tag is not empty and line-height is applied. Then when you click outside the editable area and disable inline editor that line-break string converted to `<p></p>`. This conversion created the jumping effect, because empty `<p>` has no line-height. After that, if you click inside the editor and press <kbd>backspace</kbd> the following mystery happens:
1) tinyMCE adds `<br>` inside of the empty `<p></p>` which creates the effect of adding new line-break. I didn't figure out why it's happening, but looks like a glitch in the inline tinyMCE;
2) if you press <kbd>backspace</kbd> once again, then entire string ( `<p><br/></p>` ) removed correctly.

To overcome that effect I added custom scripts which processes the empty `<p></p>` and adjust them so they can be edited/viewed correctly using inline editor.

**Comment by lots0logs** [comment]
@SlavaET I'm consistently getting this when simply pressing <kbd>Enter</kbd>, typing `Test`, and checking the module settings.
```
<p><br/></p>
<p class="et-fb-mce-line-break-holder">Test</p>
<p><br/></p>
```

**Comment by SlavaET** [comment]
@lots0logs fixed. Please check the latest version of PR.

**Comment by lots0logs** [comment]
@SlavaET 

![2016-12-09 15-32](https://cloud.githubusercontent.com/assets/4675662/21065259/e87ff1bc-be24-11e6-9c29-76599af1776e.gif)

```html
<p>Divi will change the way you build websites forever.</p>
<p>Another Test. \</p>
<p><br/></p>
<p>The advanced page builder makes it possible to build truly dynamic pages without learning code.</p>
```

**Comment by SlavaET** [comment]
@lots0logs can you please explain what's wrong there? It looks fine to me and works as expected.. 🤔

**Comment by lots0logs** [comment]
@SlavaET I was thinking that the `<p></br></p>` shouldnt have been there but looking at it again I see that is actually the intended behavior. My bad :sweat_smile:

**Comment by Jronk** [comment]
See my review in PR, thanks!

**Comment by SlavaET** [comment]
@Jronk fixed. Please check again.
