### ISSUE TITLE
Dot Navigation :: Not working in a section that is set to not show on Desktop

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#832]
### Problem:

The title pretty much explains it. 

### Steps To Reproduce:
1.  add few section to your layout (5)
2. set one of your section to "not show" on desktop
3. the dot navigation will only have 4 bullets - that's correct
4. the active bullets, doesn't work as expected.

Here is a layout for testing. I was able to replicate this issue on 2 different servers. 

Note: Section 2 is set to not show on desktop:
[Dot Navigation.json.zip](https://github.com/elegantthemes/Divi-Beta/files/640098/Dot.Navigation.json.zip)

Don't forget for the page where you will import the layout to use the Dot Navigation.

## Attached PR

- https://github.com/elegantthemes/Divi/pull/2650

**Comment by lots0logs** [comment]
@fikrirasyid Did you see [this part](https://github.com/elegantthemes/Divi/pull/2650/files#diff-e2c59e78cf79f8ab74935c5ca62a38ddR860) of that function?

**Comment by fikrirasyid** [comment]
@lots0logs ah, thank you for spotting it! I forgot to remove it which I have now done by pushing https://github.com/elegantthemes/Divi/commit/575808a57ca262f7704924e1328d6101a9f96b4c.

There are at least two reasons why it is no longer used:

1. Theoretically, it appears to anticipate a situation where the sidenav item appears while the section is hidden which shouldn't happen in the first place. I think if the appearing section is 4, the sidenav items should be 4 as well.
2. No. 1 led to how it actually works: `$target.is( ':visible' )` did and always returns `true` (and supposed to be) because number of sidenav item should equal to appearing section.
3. Furthermore, since the fix at https://github.com/elegantthemes/Divi/issues/2650 ensure that we always use visible section as the base of number of sidenav item, this makes any visibility check no longer needed, which also applies to https://github.com/elegantthemes/Divi/commit/575808a57ca262f7704924e1328d6101a9f96b4c#diff-e2c59e78cf79f8ab74935c5ca62a38ddL838.
 
Let me know if I miss anything here.

**Comment by lots0logs** [comment]
@fikrirasyid When I wrote that I was thinking that $target in that context was the actual section on the page, not one of the side nav dots

![homer-simpson-doh](https://cloud.githubusercontent.com/assets/4675662/21041308/cd025c2e-bdaf-11e6-83de-8a2e1173d885.gif)
