### ISSUE TITLE
Plugin Compatibility :: BuddyPress Pages Blank With Divi 3.0.18+

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#849]
### Problem:

BuddyPress pages (like Members, Account, etc) started showing up blank in Divi 3.0.18. They work fine in previous versions of the theme. They work fine in all of our other themes. I looked into this but the cause of the issue is not obvious. It will require advanced debugging AKA @fikrirasyid debugging :grin: 

## Attached PR
https://github.com/elegantthemes/submodule-epanel/pull/49

**Comment by fikrirasyid** [comment]
@lots0logs first of all:

>  It will require advanced debugging AKA @fikrirasyid debugging 😁

😅 I honestly don't know how to react to this 😂

***

I've tried replicating the issue and everything looks working as expected on me. Can you further elaborate what to do to replicate the issue and how it supposed to work? I'm not really fluent (yet) with BuddyPress so I might draw incorrect conclusion without detailed guidance on what to expect and how it supposed to work.

**Comment by lots0logs** [comment]
@fikrirasyid After installing and activating BuddyPress you will notice that it creates a few pages. If you view any of those pages you will see that they are empty. That is the problem. If you change themes and then view the pages you will see what they should look like.

**Comment by fikrirasyid** [comment]
@lots0logs can you share a screenshot of how the issue looks and how it should be? I've tried to replicate this on different sites, and it works as expected. After making sure that the related component is activated on `Dashboard > Settings > BuddyPress > Components` and the page is correctly assigned at `Dashboard > Settings > BuddyPress > Pages`, all the auto-generated page appears as it should be. Here are some of them:

![screen shot 2016-12-17 at 9 15 13 pm](https://cloud.githubusercontent.com/assets/916442/21287432/f72bd03a-c49d-11e6-8df8-31dcdf493658.png)

*Members Page*

![screen shot 2016-12-17 at 9 15 20 pm](https://cloud.githubusercontent.com/assets/916442/21287436/0287704c-c49e-11e6-9ac6-27c0cec09563.png)

*Activity Page*

![screen shot 2016-12-17 at 9 15 28 pm](https://cloud.githubusercontent.com/assets/916442/21287440/1302b1f2-c49e-11e6-9e82-9951f33a9943.png)

*Sites Page*

**Comment by eduard-ungureanu** [comment]
@fikrirasyid I did follow your comments, and still it doesn't show the BuddyPress content. I will attacked 3 screenshots:

BuddyPress Settings:
<img width="960" alt="screen shot 2016-12-19 at 9 46 13 am" src="https://cloud.githubusercontent.com/assets/1719735/21304791/395c7b5c-c5d0-11e6-8b25-8bd321787d22.png">

How the Members page shows on default wordpress theme:
<img width="960" alt="screen shot 2016-12-19 at 9 46 42 am" src="https://cloud.githubusercontent.com/assets/1719735/21304799/4429c788-c5d0-11e6-81aa-eadb3a8531ac.png">

How the Members page shows using Divi:
<img width="960" alt="screen shot 2016-12-19 at 9 46 57 am" src="https://cloud.githubusercontent.com/assets/1719735/21304802/4e7b4496-c5d0-11e6-9a5a-0eccd825ea85.png">


Right now I'm using a blank child theme for Divi, but the same page layout is present if I use the parent theme.

Here are the details if you like to login to me testing server:
Hi I did set up a live test server.

Please go to http://divi.wordpress-corner.com/wp-admin
User: JoeDoe
Pass: adminJoe

Thank you in advance.
Best Regards.

**Comment by fikrirasyid** [comment]
@eduard-ungureanu thank you for your test site! I finally figured out that the issue occurs whenever `Grab the first post image` option is enabled. I've attached the PR above.

**Comment by lots0logs** [comment]
@fikrirasyid I think that it would be better to implement your solution in a way that will prove beneficial in the long-term. Let's add the apply filters call in `et_get_option()` instead. We can use this format for the filter names: `et_option_{$option_name}`

**Comment by fikrirasyid** [comment]
I thought and tested about what you suggested earlier, but it created unneeded complexity for filtering because `$shortname` is included in the option key. So when you're thinking about:

```
et_option_{$option_name}
```

I'm pretty sure you think that the complete option name is:

```
et_option_grab_image
```

while the actual option name is:

```
et_option_divi_grab_image.
```

Consequently, if you'd filter `et_get_option()` output, it'll be something like:

```
return apply_filters( "et_get_option_{$option_name}", $value );
```

which means the way to filter it becomes:

```
add_filter( 'et_get_option_divi_grab_image', 'callback_func' );
```

This creates complexity in a way that either:

1. The filter callback is created on each theme, which means we should repeat this process multiple times (theoretically tho; Extra seems not to have grab image option at this point)
2. Wrap the filter hook inside another function which is hooked in `init`
3. Define global `$shortname` on `custom_functions.php`. I don't think this is a good idea tho.

Either way, it is more (unnecessarily) complicated that what I've suggested. I personally want `et_get_option()` to be filterable and believe that we'll make it filterable eventually, but for this specific issue, it makes unnecessary complication.

**Comment by lots0logs** [comment]
@fikrirasyid There is only ever one of our themes active at any given time. Therefore it matters not what the value of `$shortname` is to the consumer of the filter. Further, the entire WordPress code base is built on the concept of actions and filters. Obviously, you know that; my point is that wrapping the return value of `et_get_option()` in a call to `apply_filters()` will not have any measurable impact on performance. IMO adding code that can potentially solve many problems down the road is always preferable to adding code that solves only one problem right now. @SlavaET @Jronk What do you guys think?

**Comment by fikrirasyid** [comment]
@lots0logs regarding this:

> Obviously, you know that; my point is that wrapping the return value of et_get_option() in a call to apply_filters() will not have any measurable impact on performance

I didn't mention anything about performance. By unnecessary complication I mean the structure of the code.

> IMO adding code that can potentially solve many problems down the road is always preferable to adding code that solves only one problem right now

The existing PR actually anticipate potential future problem, as I mentioned on the comment block of the code:

> "Grab the first post image" needs to be filterable so it can be disabled forcefully. It uses et_first_image() which uses apply_filters( 'the_content' ) which could cause a conflict with third party plugin which extensively uses 'the_content' filter (ie. BuddyPress)

Due to the way `the_content` filter is used by `et_first_image()`, I think more plugin, including third party plugins that we support by default, would need to disable this grab image setting. Thus:

1. Explicit filter for this particular setting would be clearer for us and future third party developer. It basically says: "oh, your plugin plays with `the_content` and something funky happens? You might want to check out this specific setting"
2. I can see list of our own third party plugin checks grows inside `et_grab_image_setting()`. 

In retrospect, I can see the point you're making and it is pretty legit too. However I think adding specific function & filter for this potentially conflicting issue would be clearer approach. Let's see what others think for wider perspective. cc: @SlavaET @Jronk

**Comment by lots0logs** [comment]
@fikrirasyid 
>I didn't mention anything about performance. By unnecessary complication I mean the structure of the code.

I misunderstood you. Sorry! :sweat_smile: 

>Explicit filter for this particular setting would be clearer for us and future third party developer. It basically says: "oh, your plugin plays with the_content and something funky happens? You might want to check out this specific setting"

That is a good point.

**Comment by SlavaET** [comment]
I agree that adding filter into `et_get_option()` is a good idea, but I don't think we should add it in scope of this issue. This is not related to the fix and Fikri's new filter is an useful addition to his solution in this particular case.
If we're talking about ability to override theme options in general, then it's already possible. We're using `get_option()` function to retrieve the options data from WPDB and that function have a lot of filters where user may hook in and override the value for any option - https://developer.wordpress.org/reference/functions/get_option/#source
But it's still maybe useful to add filter into `et_get_option()` to make it easier for 3rd party devs.

**Comment by Jronk** [comment]
To chime in as well, I agree with the big picture here as well. 

1. There are many ways to skin this cat, but @fikrirasyid 's current PR'd way has a good level of context and specificness that lends to be more helpful in this particular situation.
2. Even with that, I agree with adding a filter to `et_get_option()`, but also as @SlavaET mentioned there are already filters higher up that still be used, even now, to change the return value of `et_get_option()`.
  a. We probably should add the filtering of that in a new/seperate issue for its own discussions etc
3. @lots0logs you are totally right about the big picture issue you are fighting for, thanks seeing it and fighting for it!
