### ISSUE TITLE
Customizer :: Background :: Stretch And Repeat/Position Should Be Mutually Exclusive

### ISSUE THREAD

**Issue by lots0logs** [elegantthemes/Divi-Beta#862]
### Problem:
When stretch background is enabled, repeat and position should be disabled/default. When repeat/position are not disabled/default then stretch background should be disabled. 

## Attached PR
- https://github.com/elegantthemes/Divi/pull/2670

**Comment by timayhelen** [comment]
When no image is applied and stretch background image is disabled. After adding an image, the correct options do not appear. They appear after toggling stretch background on and off again, however.

![strech-1](https://cloud.githubusercontent.com/assets/3333028/21552865/63dd7b42-cdb9-11e6-954c-f490f6d8bfa7.gif)

**Comment by fikrirasyid** [comment]
@timayhelen can you use smaller image to test the PR? Based on the gif you attached, it appears that you were using 1800 x 900 image which gives a fullwidth + stretched-like appearance due to the dimension of the window:

![screen shot 2017-01-05 at 7 33 58 am](https://cloud.githubusercontent.com/assets/916442/21664528/a9e274f2-d319-11e6-9df7-00ea968563ac.png)

I tested the PR using really small image and it appears that the PR works as intended:

![862-clarification](https://cloud.githubusercontent.com/assets/916442/21664542/c14db6a6-d319-11e6-992b-3ec3d0613ac5.gif)

1. no image + no stretched
2. image is added + no stretched: image is positioned correctly on top left of the background
3. image is added + stretched: image is correctly stretched

**Comment by timayhelen** [comment]
@fikrirasyid I am referring to the available options in the sidebar, not the appearance of the image. 

> When no image is applied and stretch background image is disabled. After adding an image, the correct options do not appear. They appear after toggling stretch background on and off again, however.

**Comment by fikrirasyid** [comment]
@timayhelen ah i see. I'm looking into wrong areas then :facepalm:

Thank you for confirming it, I'll work on it 👍

**Comment by fikrirasyid** [comment]
@timayhelen I've pushed https://github.com/elegantthemes/Divi/commit/979ca465c5bf3fc9e7aa6d24ff8950711f2f0680 to fix the issue mentioned at https://github.com/elegantthemes/Divi-Beta/issues/862#issuecomment-269680026. While at it, I also figured that it'd be better if `stretch background image` option is being toggled based on background image as well. Thus, the way it works now is:

`Background image` value affects the following fields' visibility (basically all background image fields):

- Stretch Background Image
- Background repeat
- Background position x
- Background position

`Stretch background image` value affects the following fields' visibility:

- Background repeat
- Background position x

![862-b](https://cloud.githubusercontent.com/assets/916442/21668453/90fed10e-d334-11e6-849b-258429836c11.jpg)

![862](https://cloud.githubusercontent.com/assets/916442/21668454/91044fbc-d334-11e6-99c7-779faab7d6ca.jpg)

**Comment by Jronk** [comment]
See PR review

**Comment by fikrirasyid** [comment]
@Jronk I've incorporated your feedbacks at https://github.com/elegantthemes/Divi/commit/7e47f739df9d714951eca943d30259ff1c6416e7

**Comment by Jronk** [comment]
@fikrirasyid great thanks!
