### ISSUE TITLE
Timeout error when woocommerce enabled

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#866]
Can anyone take a look why Visual Divi Builder pops up Timeout error message only when woocommerce is enabled? I can't find out where the problem comes from.

It's the latest divi theme and wordpress 5.6.25. Memore limit and other options are fine.
http://purehomespun.com

Ask me for a token if you need,
Thank you. 

Ticket: https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=630512

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1547

**Comment by fikrirasyid** [comment]
@kary4 can you PM me the token over Slack? I think I have a theory in mind that I need to check about this issue.

**Comment by kary4** [comment]
Sure, thank you!

**Comment by fikrirasyid** [comment]
@kary4 @lots0logs I've figured out what actually happens, but I'm still working on a decent fix for this. In summary, this is what happens:

1. User sets page titled "home" as its home page, as defined from `Dashboard > Settings > Reading > Front Page Displays`
2. User sets the same page (home) as its WooCommerce's Shop Page, as defined from `Dashboard > WooCommerce > Settings > Products > Shop Page`
3. This causes homepage loads the `home` page, but instead of using Divi's page template, it uses WooCommerce's shop page template. This explains why http://purehomespun.com/'s homepage has sidebar despite of using Divi and it has no custom page template defined
4. This further causes VB to load the actual page instead of empty div wrapper for VB placeholder, which further causes error popup to appear.

Note: This issue can be replicated  on any installation.

While I'm still working for a patch for this issue (which will take sometime until we released it due to reviewing cycle), you can advise user to remove the shop page setting on `Dashboard > WooCommerce > Settings > Products > Shop Page`. Simply click the (x) icon on Shop Page's select UI then save the page..

**Comment by lots0logs** [comment]
@fikrirasyid A similar situation frequently comes up in the forum which is when customers configure the shop page they created with the builder as their shop page in woocommerce settings. Is there anything we can do to prevent this situation, or at least make the user aware that they are `doing_it_wrong()`?

**Comment by fikrirasyid** [comment]
@lots0logs I'm still working on it. The main issue is VB works on `is_page()` condition, while shop page is basically turns the selected page into `is_archive()` condition.

>  Is there anything we can do to prevent this situation, or at least make the user aware that they are doing_it_wrong()

I initially thought to use the `make the user aware that they are doing_it_wrong()` approach, but as I think of it, it makes the experience of VB isn't really intuitive. I'm still looking for a better and intuitive approach for it.

**Comment by fikrirasyid** [comment]
@lots0logs please take a look at https://github.com/elegantthemes/submodule-builder/pull/1547. I think this is the most intuitive solution: adapt embrace to the way WooCommerce displays `post_content`.

**Comment by fikrirasyid** [comment]
@lots0logs UX wise, I think using shop module as dependency would make it super weird, especially when we consider that user can add / remove shop module in real time using visual builder. While I'm sure your assumption on this might be accurate:

> 99.9% of the time, first-time users of the Shop Module will attempt to set the custom shop page, that they created with the builder, as their shop page in WC settings (with the desired result being that their shop page is the one that they created with the builder)

I thought that it'd be better to educate the user that shop page carries the consequence which is what user saw right now (WC templating). However as I think more about this, the UX would be bad and we'll need to answer lots of user answer regarding it.

The middle ground on this, I think, if builder is activated for shop page, simply take over the page and let shop module uses the shop module's query. Shop module is "archive for product", so let's say we make the builder on that page behaves like Extra's category builder. What do you think?

**Comment by lots0logs** [comment]
@fikrirasyid 
> I think, if builder is activated for shop page, simply take over the page and let shop module uses the shop module's query.

That's actually what I meant in my previous comment, I guess I didn't explain myself well (sorry :sweat_smile: )

**Comment by fikrirasyid** [comment]
@lots0logs updated. Please read the updated PR message on how the patch works.

**Comment by lots0logs** [comment]
@fikrirasyid Could we rename the new directory to `compat` instead?

**Comment by fikrirasyid** [comment]
@lots0logs 

> Could we rename the new directory to compat instead?

done.

> I'm still testing the changes and so far they dont appear to be working for me at all. 

Have you tried this note I mentioned at the PR's message?

> If you tested the branch and found the page won't being updated, try flushing the permalink cache by opening `Dashboard > Settings > Permalink` page.

**Comment by lots0logs** [comment]
@fikrirasyid I realized what I was doing the first time I tested it..I was viewing the page using its permalink instead of using `/shop` to access it. If you access it via `/shop` then it works perfectly. If you access it using the original permalink then it doesn't render the page correctly. 

Also I noticed that when the shopping cart is empty, the Return To Shop button links to the page's original permalink instead of linking to `/shop`.

**Comment by fikrirasyid** [comment]
@lots0logs hmm... I don't understand why you separate `/shop` and "`original permalink`". "Shop page" is basically whatever page you're configuring at `Dashboard > WooCommerce > Settings > Products > Display > Shop Page`:

![screen shot 2017-01-06 at 9 21 10 am](https://cloud.githubusercontent.com/assets/916442/21705284/a01eef80-d3f1-11e6-9fe2-e5ad3b4ff337.png)

Which regarding this:

> Also I noticed that when the shopping cart is empty, the Return To Shop button links to the page's original permalink instead of linking to /shop

If you have different page configured for the "shop page", it is expected for the "Return To Shop" link to point to whatever page you are configuring shop page as well:

![screen shot 2017-01-06 at 9 23 34 am](https://cloud.githubusercontent.com/assets/916442/21705366/1c571dca-d3f2-11e6-9562-b03e2ed39d37.png)

Is there something that I'm missing?

**Comment by lots0logs** [comment]
@fikrirasyid I might be wrong but AFAIK, this is how WooCommerce Shop Page works:

1. Let's say you create a page titled **My Shop Page**. After publishing the page, it is accessible at `http://yoursite.com/my-shop-page`
2. Then you go to WC settings and set the "Shop" page to be the page you just created:

![2017-01- 5_09-45-09-pm](https://cloud.githubusercontent.com/assets/4675662/21707071/a7396738-d391-11e6-8d3e-278cacfaddfe.png)
Note: Let's pretend the selected page in the above screenshot is **My Shop Page** (so I dont have to take a new screenshot to finish explaining this :sweat: )

If you have the default settings for WC in `Settings>>Permalinks` then your WC shop page will be accessible at: `http://yoursite.com/shop`. Regardless of which page you assigned to be your shop, the page will be accessed at ` http://yoursite.com/shop`:

![2017-01- 5_09-45-38-pm](https://cloud.githubusercontent.com/assets/4675662/21707063/93c6fd78-d391-11e6-8fc8-945381103092.png)


Now, all of this is fine. It works as it should on your branch. There's just one issue which is what happens when you try to navigate to `http://yoursite.com/my-shop-page`. You will see the result is a broken layout. Really it wouldnt be something to worry about if it wasn't for the fact that the "Back To Shop" button on the empty cart page points to `http://yoursite.com/my-shop-page`. The button should point to ` http://yoursite.com/shop` (or whataver the shop base is configured to be in `Settings>>Permalinks`)

**Comment by fikrirasyid** [comment]
@lots0logs ah I see. I think we have a different understanding on what `Dashboard > Settings > Permalink` setting does. As far as I know (and I've re-checked it to WooCommerce's docs: https://docs.woocommerce.com/document/permalinks/) `Dashboard > Settings > Permalink` has nothing to do with defining product archive page. It only deals with **singular product item page permalink**. Its job is to enable user to change this default singular product page permalink structure for example from:

```
http://woocommerce.com/product/product-name
```

into:

```
http://woocommerce.com/custom-stuff-here/product-name
```

And by configuring this, it won't change `http://woocommerce.com/custom-stuff-here/` into product archive product.

***

To validate my point above, I tested the exact steps you mentioned above on new site using twenty sixteen theme:

![screen shot 2017-01-06 at 11 18 11 am](https://cloud.githubusercontent.com/assets/916442/21707470/f401a0b0-d401-11e6-92e4-7b1c34a8e642.png)

![screen shot 2017-01-06 at 11 19 33 am](https://cloud.githubusercontent.com/assets/916442/21707481/1a895714-d402-11e6-82bb-1f7ec087763f.png)

![screen shot 2017-01-06 at 11 20 28 am](https://cloud.githubusercontent.com/assets/916442/21707493/3ae3c6a2-d402-11e6-8226-3e62d20116b2.png)

Now go to the permalink:

![screen shot 2017-01-06 at 11 21 29 am](https://cloud.githubusercontent.com/assets/916442/21707537/9b66d5aa-d402-11e6-8d07-c9918481cd1f.png)

![screen shot 2017-01-06 at 11 24 06 am](https://cloud.githubusercontent.com/assets/916442/21707550/bdfc42e4-d402-11e6-8c8f-96ba2bd0b4c5.png)

![screen shot 2017-01-06 at 11 24 55 am](https://cloud.githubusercontent.com/assets/916442/21707567/dfeca45c-d402-11e6-9ede-e7ac003a8ab8.png)

Now you might have a question: how to make site.com/shop as product archive page then? The answer is:

1. Create a page named `shop`. Make sure its permalink is `site.com/shop`
2. Assign it as shop page via `Dashboard > WooCommerce > Settings > Products > Display > Shop Page`

**Comment by lots0logs** [comment]
@fikrirasyid You were right :1st_place_medal:  But its still not working for me. The result is the same as I mentioned in https://github.com/elegantthemes/Divi-Beta/issues/866#issuecomment-269699415 You can log into my test site and check it out, just let me know when you do so I can make sure its on the right branch.

**Comment by fikrirasyid** [comment]
@lots0logs Sure, can you PM me your test site via slack?

**Comment by fikrirasyid** [comment]
@lots0logs it turned out that my previous patch has a flaw in it: I missed flushing permalink after setting shop page which causes incomplete setup which cause me to miss the issue that appear on your test site. I've pushed a fix for the PR (see https://github.com/elegantthemes/submodule-builder/commit/be9e146aabe15c65893155a990921724f3944774 for the detail explanation) and tested it on your test site using WPIDE to directly change the changed file. It looks good now. 

It'd be awesome if you re-test the PR by pulling the latest branch from repo. Let me know if you're still encountering any issue.

**Comment by lots0logs** [comment]
@fikrirasyid Looks, good but I found one small issue with buttons that appear inside the Sidebar Module:

![2017-01-09 12-12](https://cloud.githubusercontent.com/assets/4675662/21777568/f9ae762c-d664-11e6-9df8-c0908f2ea62e.gif)

**Comment by fikrirasyid** [comment]
@lots0logs can we open new ticket for that? I know it is a relatively small issue, but it is quite unrelated with what this issue is.
