### ISSUE TITLE
Divi Builder :: Cloning Sections on Safari

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#879]
### Problem:

Using the latest version of Safari on a Mac OS Sierra, I cannot clone section when the layout become more complicated.

To best ilustrate the issue, please check out this screenshot:
https://drive.google.com/open?id=0B8PjD3Z_XQvuQldtdmxBMm9peVE

Everything works in Chrome or Firefox.

**Comment by SlavaET** [comment]
I checked the issue and looks like it happens due to LocalStorage overflow which size in Safari is significantly less than localstorage size in Chrome and Firefox. I checked the capacity of localstorage on this website - https://arty.name/localstorage.html and get the following results:
Chrome - `5200000 characters`
FireFox - `5200000 characters`
Safari - `2600000 characters`
So theoretically you can overflow the localstorage in any browser with a crazy amount of modules on page, but it's easier to overflow the localstorage in Safari. Localstorage overflow causes js error when you try to copy/duplicate item which breaks the Backend Builder. Moreover if you use the Safari in Private Mode then localstorage will not be available at all.
The things we need to consider in order to fix this issue:
1)  We need to determine whether the localstorage have enough space to store the item. For ex. wrap the `localStorage.setItem()` into `try { } catch() {}` and catch the errors at this point;
2) If we cannot use `localStorage.setItem()` then fallback to simple system for copy/duplicate which will not use the LocalStorage and will only work in scope of a single page and single user session. We don't have this system, so it should be developed.

I see the following benefits of the above fix:
1) We'll fix the error in Safari ( and possibly in other browsers with small amount of available localstorage space );
2) Browsers without localstorage support will also support copy/duplicate feature in BB which is not the case right now.

@Jronk @timayhelen does this option sounds ok to you? If yes, I'll implement such a system or maybe you have some more ideas how to improve it.

**Comment by timayhelen** [comment]
@SlavaET I think it sounds like a good solution, but let's wait to implement it for now. I am going to move this to low priority and change it to an improvement update.

**Comment by johncuk** [comment]
I found this while trying to fix an ongoing issue I've been having duplicating modules on my website. It seems that many other (if not all)  Safari users have the same issue. Moving to Chrome as had been suggested on the ElegantThemes support forum is not a fix.

I'm both surprised and disappointed that this has been flagged as an improvement rather than a bug. It did work, it doesn't now....the buttons are still there on Safari so if it doesn't work surely it's a bug plain and simple!?

**Comment by colinmcdermott** [comment]
This just caused issues during a training session with client, would be great to get fixed.

**Comment by edgar-sanchez-is** [comment]
I'm also having this issue on Safari.

**Comment by johncuk** [comment]
This is still an issue. Could someone explain why it's been closed please?

**Comment by edgariscoding** [comment]
I’m still having this issue, was it fixed or why was it closed?

**Comment by Krable55** [comment]
Looks like this will continue to be an ongoing issue. "We'll fix it later" seems to be their official response.

**Comment by lots0logs** [comment]
Hi, sorry for the delayed response. This repo is only used during Divi beta testing. The proper place to report issues that aren't for beta tests is our [Support Forum](https://www.elegantthemes.com). Thanks for your cooperation :smiley:
