### ISSUE TITLE
Theme Customizer :: Background Alpha Slider Is not Displaying Corrctly

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#888]
### Problem:
This issue was fixed previously but it's back again. It's not possible to select opacity value in Alpha Slider  under Theme Customizer>Header & Navigation > Primary Menu Bar > Background Color. I saw a lot of users in the facebook divi group:
https://www.facebook.com/photo.php?fbid=1719659305015903&set=g.494980220631579&type=1&theater

![artwork richard slechta - mozilla firefox](https://cloud.githubusercontent.com/assets/3352130/21847096/1d80c8dc-d80b-11e6-942a-711b48ea4518.jpg)

**Comment by timayhelen** [comment]
This has been a random issue since forever ago. I think it's related to the JS calculations and the fact that fractions of pixels are used in the width and margins of the color picker elements. I added a negative -1px margin to the the first two items in the row to give the whole element just a bit of wiggle room. I think it will fix the issue.
