### ISSUE TITLE
Contact Form Module Optional Field Type Sending Field Title in the Mail

### ISSUE THREAD

**Issue by abhi-sharm** [elegantthemes/Divi-Beta#902]
### Problem:
If we make a field as optional and if the user fills it, we receive it properly in the mail but if the user does not fill that field, in the email received we see the title (placeholder) of the field itself, Ideally, it should come as blank in received email. Not sure if it is designed this way for some reason or it is some recent bug. One customer reported this and I was able to replicate with latest Divi 

### Steps To Reproduce:
1.  Make a contact form and add an additional field in it , like phone number
2.  make this new field optional
3. fill the form but do not fill any data in this field

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1575

**Comment by lceberg** [comment]
The issue comes from the fact that fields currently use their "value" attribute for placeholder (which is hidden with JavaScript on focus if it matches the field title).

The attached PR removes this implementation in favor of native HTML "placeholder" attributes, the value of which is not being sent in the email.
