### ISSUE TITLE
Shop Module :: Issue with sorting products by category

### ISSUE THREAD

**Issue by FaycalBoutam** [elegantthemes/Divi-Beta#903]
### Problem:

When using the Shop module and sort products by a category (by date), the products are displayed from oldest to newest. I think it should be the opposite by default, or add two options (ASC and DESC).

![1](https://cloud.githubusercontent.com/assets/16414613/21898021/4f05aafc-d8e3-11e6-8133-ed63b4f60950.png)

![2](https://cloud.githubusercontent.com/assets/16414613/21898025/53018bc6-d8e3-11e6-9e1b-164d6a94fa55.png)
 
## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1847

**Comment by lceberg** [comment]
After looking into this it turned out the [WooCommerce shortcode](https://docs.woocommerce.com/document/woocommerce-shortcodes/) that we use behind the scenes orders the products in ascending order by default (which I agree is not very intuitive).

As we don't currently explicitly specify the order direction (ASC/DESC) when generating the shortcode we can implement a select field for this, but this brings another issue -- the order has no effect on "Best Selling" and "Top Rated" products.

I was thinking of showing the select only on modes that are affected by the order, but the builder's conditional logic currently doesn't seem to support that (ie. we can show it when the value of a field is X, but we can't show it if the value is **either** X, Y or Z).

A less pretty solution would be to just force descending order on all modes.

@timayhelen please let me know what do you think.

**Comment by timayhelen** [comment]
@lceberg I think it would make the most sense to expand our conditional logic to allow for "or" statements, and then we can implement the order option correctly.

**Comment by FaycalBoutam** [comment]
> Why hasn't this SIMPLE issue been fixed? Not fixing this issue is making a LOT of customer lose sales!!! And it is PISSING my customers off, which in turn is pissing me off!!

**Comment by sinegrain** [comment]
Hi guys here a workaround for who's hurry :)

I modified the code found here:
https://gist.github.com/mikejolley/1622323#gistcomment-141364

as following (and it works) :

//in function.php of your theme

add_filter('woocommerce_get_catalog_ordering_args', 'am_woocommerce_catalog_orderby');

function am_woocommerce_catalog_orderby( $args ) {
    $args['orderby'] = 'date';
    $args['order'] = 'desc'; 
    return $args;
}

**Comment by FaycalBoutam** [comment]
The customer is really frustrated with this issue. 

> Yet, ANOTHER Divi update and the sorting by date issue is STILL NOT resolved. 
> 
> I reported this issue back one JANUARY 9, 2017 - it is now MARCH 21, 2017. Bug is STILL NOT fixed.
> 5 updates since the first reporting of a bug and it is still not resolved. This is ridiculous.
> 
> Your developers cannot fix a simple sorting issue?
> 
> Matter of fact it sorts in reverse order. If I date my products way far back, they become the first product(s) shown. Newest products are the last ones shown.
> 
> This bug is not only hurting eCommerce store owners but, my web clients as well.

**Comment by lceberg** [comment]
> The customer is really frustrated with this issue.

Technically not an issue, since WooCommerce [enforces this behavior by default](https://docs.woocommerce.com/document/woocommerce-shortcodes/#section-12). 😞 

As this seems to be causing problems for some clients PR adds an "Order" select (without conditional logic) which provides options for sorting order _for shop types that support it._

Defaults to "Default Sorting" which doesn't change the current functionality (for backwards compatibility).

@timayhelen Maybe we can go with this solution for the time being and open a new issue for expanding the conditional logic ?

**Comment by lots0logs** [comment]
@lceberg The only option that the order seems to have any affect on is By Date. Considering that, I think it'd be better to simply include two date options in the existing field instead of adding a separate field. So similar to how it currently has:

* Sort By Price: Low To High
* Sort By Price: High To Low

we could use:

* Sort By Date: Oldest To Newest
* Sort By Date: Newest To Oldest

**Comment by lceberg** [comment]
@lots0logs I added the options as you suggested and removed the "Order" field. The existing logic is also tweaked a bit to support this change.

**Comment by FaycalBoutam** [comment]
> Why is Elegant Themes ignoring this fix? Yet another Divi update was released an this BUG is still NOT fixed. WTF is the problem here?
> 
> This bug is almost SIX MONTHS old.
> 
> This is the worst case of customer service anywhere. I am going to start copying and pasting this entire thread and share it on review boards. #pathetic

**Comment by FaycalBoutam** [comment]
@timayhelen

**Comment by Jronk** [comment]
@FaycalBoutam this has been merged into master, so it will go out with next release :whew:
