### ISSUE TITLE
Slider Module Padding Doesn't Get Updated When Being Updated

### ISSUE THREAD

**Issue by eduard-ungureanu** [elegantthemes/Divi-Beta#935]
### Problem:

Not sure if this is an issue with the new functionality or not, but when in Visual Builder and set a top / bottom padding on the slider, the changes are not visible - the slider doesn't change it's height, switching to the backend builder tab - the new settings are saved - saving the settings again in the backend builder and checking the visual builder tab will update the new settings, and the slider will have a new height (depending on the values used for the top/bottom padding).

https://drive.google.com/open?id=0B8PjD3Z_XQvuRENPWlhLdE45c0k

**Comment by fikrirasyid** [comment]
This issue isn't builder sync-specific since the same issue occurs on `master`. I was about to submit https://github.com/elegantthemes/submodule-builder/issues/1720 but it turns out the issue has been fixed on different PR and has been merged to `master` as I submit the PR.

Thus, let's close this in favour of the merged https://github.com/elegantthemes/submodule-builder/commit/b3ab665f6f3bd0e3be9c3990722ff206a63a4b3d.
