### ISSUE TITLE
Call To Action Module :: Max Width Option Does Not Update

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#962]
### Problem:
When you define Max Width option under BB then you cannot change the value in VB.

Screen cast:
http://youtu.be/hHkVGnG2t-o?hd=1

**Comment by fikrirasyid** [comment]
@karya can you clear your browser cache and try this again? I've tried replicated this issue but it appears to work as expected on latest `575-fix-heartbeat-content-smashing-wip` branch now:

![962-issue](https://cloud.githubusercontent.com/assets/916442/22938095/51d0f2f2-f30d-11e6-859c-027085e83efa.gif)

**Comment by kary4** [comment]
@fikrirasyid Actually I'm testing the things on the test server that Nick created, so I'm not sure builder is on the latest branch or not. As for now, I can still reproduce the issue here:
http://elegantthemessiteground.com/issue-962/?et_fb=1

**Comment by kary4** [comment]
I just found out it's not anything specific in CTA module but I think it's all the modules with the same problem. I just replicated similar problem in shop module:
http://youtu.be/EAzYhjY9ohg?hd=1

So, here is the exact steps to reproduce this problem:
1. Create a new page > Enable Divi builder > Add only a row module >Save the page;
2. Open VB in a new tab > add shop module (don't close shop settings window);
3. Go back to BB (wait while the page syncs) > open the shop module settings;
4. Go back to BB > click save changes (in opened shop settings) > Open the settings again.
5. Go back to BB > wait the sync > close the settings by clicking Save button.
6. Go to VB and you can see the problem.

I'm sorry the steps I described above look confusing. You'll see the real problem in the screen cast above.

**Comment by fikrirasyid** [comment]
@kary4 ah, I think I get what you mean:

1. Open a page on VB and BB
2. Open VB settings modal
3. Switch to BB
4. Open the same settings modal, save, and let it sync
5. Switch to VB, let it sycned
6. The settings modal now can't be edited

This issue is essentially similar to:

1. https://github.com/elegantthemes/Divi-Beta/issues/974
2. And this sub-issue: https://github.com/elegantthemes/Divi-Beta/issues/945#issuecomment-280022610

To cover them, we have https://github.com/elegantthemes/submodule-builder/pull/1718 under review now. I've thoroughly explained what actually happens and what the limitation of our situation.

I'm closing this issue for now then. If you feel that this issue is essentially different from the issues above, feel free to re-open it and let me know what do you think about it.
