### ISSUE TITLE
A Few Problems After Internet Was Disconnected

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#972]
### Problem:

1. Everything freezes under Visual Builder.
2. When you open VB from BB nothing appears.

To replicate the problems:

1. Add some changes under VB;
2. Disconnect your Internet;
3. Click Exit Visual Builder (You'll see first problem);
4. Connect your Internet;
5. Activate BB Tab and try to open VB in a new Tab (You'll see the 2nd problem).

Screen cast:
http://youtu.be/LncwkSgzuDQ?hd=1

## Attached PR
- https://github.com/elegantthemes/submodule-builder/pull/1742

**Comment by fikrirasyid** [comment]
I've submitted https://github.com/elegantthemes/submodule-builder/pull/1742 to fix this issue but there are several things that need to be noted:

1. "Everything freezes under Visual Builder." is actually transparent pre-loader overlay that wasn't stopped / removed once the unsaved notification appears. Properly remove the preloader when unsaved notification appears fixes this issue
2. "When you open VB from BB nothing appears" is actually "nothing is being saved". If the page previously has a layout, that layout will appear. Autosave doesn't kick in because it hasn't reach the heartbeat interval (15, 30, 45, or 60 seconds) and no window blur-based force autosave was triggered. Thus, this is actually expected. Ideally, the "download backup" option should look for browser based backup if server cannot be contacted like what is happening on this ticket report. It is still work in progress tho. Please see: https://github.com/elegantthemes/Divi-Beta/issues/949#issuecomment-280220947
