### ISSUE TITLE
VB Does Not Sync 

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#975]
### Problem:

In some cases VB does not update values.

To reproduce the problem please follow the steps you can see in the screen cast below:
http://youtu.be/DkrsLmwtM-s?hd=1

**Comment by fikrirasyid** [comment]
This issue is actually inevitable due to the way Backbone and React works. In general:

1. In VB (which uses react) everything is updated (near) real time. Once you change a value, that value is being queued to be immediately synced
2. BB (which uses backbone) uses different approach. The queue for sync and essentially other data updating sequence is performed *when the modal's save button is clicked*. This makes total sense because it doesn't need to re-generate preview area in real time. Thus, the shortcode structure is rebuilt (and being queued for syncing) whenever the modal is closed by clicking the save changes button.


@timayhelen @kary4 what do you guys think? I think this is a wontfix and it'd be safe to be closed. However, let me know if you guys have different point of view on this.

***

Related to disappearing modal overlay when VB content is being synced to BB with opened settings modal at https://youtu.be/DkrsLmwtM-s?t=42, please take a look at https://github.com/elegantthemes/submodule-builder/pull/1718.

**Comment by timayhelen** [comment]
I think we can ignore this for now.
