### ISSUE TITLE
ET About me Widget not parsing image URL

### ISSUE THREAD

**Issue by vukvukovich** [elegantthemes/Divi-Beta#978]
### Problem:

ET About me Widget is not parsing image URL if it is containing more than two dots. 
For example: www.example.co.uk

### Steps To Reproduce:
1.  Set widget as active
2. Put in image field URL: www.example.co.uk
3. Inspect element in frontend
4. Go back and change URL to: www.example.com
5. Inspect element in frontend

**Comment by fikrirasyid** [comment]
@vukvukovich I've tried to reproduce the issue on latest Divi but it appears to be working as expected:

![978-issue](https://cloud.githubusercontent.com/assets/916442/23536422/4edc0aea-fff7-11e6-8f69-61aba233f0fb.jpg)

Can you check it again? Furthermore, can I know why you try to use URL to a site while the field is meant for valid image address since the URL will be added on `<img src="" />`?

**Comment by vukvukovich** [comment]
@fikrirasyid Hm.. strange, it seems I cannot replicate it too now. 
Lets close it than, we will see if it pops out in maybe different use case.

Best,
Vuk
