### ISSUE TITLE
Builder Sync :: Background Moday Overlay Disappears

### ISSUE THREAD

**Issue by kary4** [elegantthemes/Divi-Beta#980]
### Problem:

When you go from VB to BB (it should be module settings window  opened) the **.et_pb_modal_overlay** disappears after syncing. 

To reproduce the problem (better check the screen cast below :) ):

1. Create a new page > Enable Divi builder > Add only a row module >Save the page;
2. Open VB in a new tab > add shop module (don't close shop settings window);
3. Go back to BB (wait while the page syncs) > open the shop module settings;
4. Go back to BB > click save changes (in opened shop settings) > Open the settings again.
5. Go back to BB > wait the sync > close the settings by clicking Save button.
6. Go to VB and you can see the problem.

I'm sorry the steps I described above look confused. You'll see the real problem in the screen cast:
http://youtu.be/EAzYhjY9ohg?hd=1

**Comment by fikrirasyid** [comment]
This issue has been addressed on https://github.com/elegantthemes/submodule-builder/pull/1718 which is made to fix https://github.com/elegantthemes/Divi-Beta/issues/974. The expected behaviour on that branch is that on BB, upon syncing, the modal and its overlay will be closed. Please read the PR message for full explanation + known limitation.
